xss:xss.cpp
	@g++ -std=c++17 -o xss xss.cpp -lcurl -lpthread -ljsoncpp
sql:sql.cpp
	@g++ -std=c++17 -o sql sql.cpp -lcurl -lpthread -ljsoncpp
dos:dos.cpp
	@g++ -std=c++17 -o dos dos.cpp -lcurl -lpthread -ljsoncpp
.PHNOY:clean
clean:
	@rm xss sql dos