// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: judge_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_judge_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_judge_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_judge_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_judge_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_judge_5fservice_2eproto;
namespace oj_judge {
class DockerWorkDoneRequest;
struct DockerWorkDoneRequestDefaultTypeInternal;
extern DockerWorkDoneRequestDefaultTypeInternal _DockerWorkDoneRequest_default_instance_;
class GetStatusRequest;
struct GetStatusRequestDefaultTypeInternal;
extern GetStatusRequestDefaultTypeInternal _GetStatusRequest_default_instance_;
class JudgeResult;
struct JudgeResultDefaultTypeInternal;
extern JudgeResultDefaultTypeInternal _JudgeResult_default_instance_;
class NullRsp;
struct NullRspDefaultTypeInternal;
extern NullRspDefaultTypeInternal _NullRsp_default_instance_;
class SubmitRequest;
struct SubmitRequestDefaultTypeInternal;
extern SubmitRequestDefaultTypeInternal _SubmitRequest_default_instance_;
class TestCaseResult;
struct TestCaseResultDefaultTypeInternal;
extern TestCaseResultDefaultTypeInternal _TestCaseResult_default_instance_;
}  // namespace oj_judge
PROTOBUF_NAMESPACE_OPEN
template<> ::oj_judge::DockerWorkDoneRequest* Arena::CreateMaybeMessage<::oj_judge::DockerWorkDoneRequest>(Arena*);
template<> ::oj_judge::GetStatusRequest* Arena::CreateMaybeMessage<::oj_judge::GetStatusRequest>(Arena*);
template<> ::oj_judge::JudgeResult* Arena::CreateMaybeMessage<::oj_judge::JudgeResult>(Arena*);
template<> ::oj_judge::NullRsp* Arena::CreateMaybeMessage<::oj_judge::NullRsp>(Arena*);
template<> ::oj_judge::SubmitRequest* Arena::CreateMaybeMessage<::oj_judge::SubmitRequest>(Arena*);
template<> ::oj_judge::TestCaseResult* Arena::CreateMaybeMessage<::oj_judge::TestCaseResult>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace oj_judge {

// ===================================================================

class SubmitRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj_judge.SubmitRequest) */ {
 public:
  inline SubmitRequest() : SubmitRequest(nullptr) {}
  ~SubmitRequest() override;
  explicit PROTOBUF_CONSTEXPR SubmitRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SubmitRequest(const SubmitRequest& from);
  SubmitRequest(SubmitRequest&& from) noexcept
    : SubmitRequest() {
    *this = ::std::move(from);
  }

  inline SubmitRequest& operator=(const SubmitRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SubmitRequest& operator=(SubmitRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SubmitRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SubmitRequest* internal_default_instance() {
    return reinterpret_cast<const SubmitRequest*>(
               &_SubmitRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SubmitRequest& a, SubmitRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SubmitRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SubmitRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SubmitRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SubmitRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SubmitRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SubmitRequest& from) {
    SubmitRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SubmitRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj_judge.SubmitRequest";
  }
  protected:
  explicit SubmitRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQuestionIdFieldNumber = 2,
    kCodeFieldNumber = 4,
    kLanguageFieldNumber = 5,
    kCustomInputFieldNumber = 7,
    kSubmissionIdFieldNumber = 1,
    kUserIdFieldNumber = 3,
    kIsCustomTestFieldNumber = 6,
    kTimeLimitFieldNumber = 8,
    kMemoryLimitFieldNumber = 9,
  };
  // string question_id = 2;
  void clear_question_id();
  const std::string& question_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_question_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_question_id();
  PROTOBUF_NODISCARD std::string* release_question_id();
  void set_allocated_question_id(std::string* question_id);
  private:
  const std::string& _internal_question_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_question_id(const std::string& value);
  std::string* _internal_mutable_question_id();
  public:

  // string code = 4;
  void clear_code();
  const std::string& code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_code();
  PROTOBUF_NODISCARD std::string* release_code();
  void set_allocated_code(std::string* code);
  private:
  const std::string& _internal_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_code(const std::string& value);
  std::string* _internal_mutable_code();
  public:

  // string language = 5;
  void clear_language();
  const std::string& language() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_language(ArgT0&& arg0, ArgT... args);
  std::string* mutable_language();
  PROTOBUF_NODISCARD std::string* release_language();
  void set_allocated_language(std::string* language);
  private:
  const std::string& _internal_language() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_language(const std::string& value);
  std::string* _internal_mutable_language();
  public:

  // string custom_input = 7;
  void clear_custom_input();
  const std::string& custom_input() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_custom_input(ArgT0&& arg0, ArgT... args);
  std::string* mutable_custom_input();
  PROTOBUF_NODISCARD std::string* release_custom_input();
  void set_allocated_custom_input(std::string* custom_input);
  private:
  const std::string& _internal_custom_input() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_custom_input(const std::string& value);
  std::string* _internal_mutable_custom_input();
  public:

  // uint32 submission_id = 1;
  void clear_submission_id();
  uint32_t submission_id() const;
  void set_submission_id(uint32_t value);
  private:
  uint32_t _internal_submission_id() const;
  void _internal_set_submission_id(uint32_t value);
  public:

  // uint32 user_id = 3;
  void clear_user_id();
  uint32_t user_id() const;
  void set_user_id(uint32_t value);
  private:
  uint32_t _internal_user_id() const;
  void _internal_set_user_id(uint32_t value);
  public:

  // bool is_custom_test = 6;
  void clear_is_custom_test();
  bool is_custom_test() const;
  void set_is_custom_test(bool value);
  private:
  bool _internal_is_custom_test() const;
  void _internal_set_is_custom_test(bool value);
  public:

  // int32 time_limit = 8;
  void clear_time_limit();
  int32_t time_limit() const;
  void set_time_limit(int32_t value);
  private:
  int32_t _internal_time_limit() const;
  void _internal_set_time_limit(int32_t value);
  public:

  // int32 memory_limit = 9;
  void clear_memory_limit();
  int32_t memory_limit() const;
  void set_memory_limit(int32_t value);
  private:
  int32_t _internal_memory_limit() const;
  void _internal_set_memory_limit(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:oj_judge.SubmitRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr question_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr code_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr language_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr custom_input_;
    uint32_t submission_id_;
    uint32_t user_id_;
    bool is_custom_test_;
    int32_t time_limit_;
    int32_t memory_limit_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_judge_5fservice_2eproto;
};
// -------------------------------------------------------------------

class DockerWorkDoneRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj_judge.DockerWorkDoneRequest) */ {
 public:
  inline DockerWorkDoneRequest() : DockerWorkDoneRequest(nullptr) {}
  ~DockerWorkDoneRequest() override;
  explicit PROTOBUF_CONSTEXPR DockerWorkDoneRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DockerWorkDoneRequest(const DockerWorkDoneRequest& from);
  DockerWorkDoneRequest(DockerWorkDoneRequest&& from) noexcept
    : DockerWorkDoneRequest() {
    *this = ::std::move(from);
  }

  inline DockerWorkDoneRequest& operator=(const DockerWorkDoneRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DockerWorkDoneRequest& operator=(DockerWorkDoneRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DockerWorkDoneRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DockerWorkDoneRequest* internal_default_instance() {
    return reinterpret_cast<const DockerWorkDoneRequest*>(
               &_DockerWorkDoneRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DockerWorkDoneRequest& a, DockerWorkDoneRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DockerWorkDoneRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DockerWorkDoneRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DockerWorkDoneRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DockerWorkDoneRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DockerWorkDoneRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DockerWorkDoneRequest& from) {
    DockerWorkDoneRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DockerWorkDoneRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj_judge.DockerWorkDoneRequest";
  }
  protected:
  explicit DockerWorkDoneRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // @@protoc_insertion_point(class_scope:oj_judge.DockerWorkDoneRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_judge_5fservice_2eproto;
};
// -------------------------------------------------------------------

class NullRsp final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:oj_judge.NullRsp) */ {
 public:
  inline NullRsp() : NullRsp(nullptr) {}
  explicit PROTOBUF_CONSTEXPR NullRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NullRsp(const NullRsp& from);
  NullRsp(NullRsp&& from) noexcept
    : NullRsp() {
    *this = ::std::move(from);
  }

  inline NullRsp& operator=(const NullRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline NullRsp& operator=(NullRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NullRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const NullRsp* internal_default_instance() {
    return reinterpret_cast<const NullRsp*>(
               &_NullRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(NullRsp& a, NullRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(NullRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NullRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NullRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NullRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const NullRsp& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const NullRsp& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj_judge.NullRsp";
  }
  protected:
  explicit NullRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:oj_judge.NullRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_judge_5fservice_2eproto;
};
// -------------------------------------------------------------------

class TestCaseResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj_judge.TestCaseResult) */ {
 public:
  inline TestCaseResult() : TestCaseResult(nullptr) {}
  ~TestCaseResult() override;
  explicit PROTOBUF_CONSTEXPR TestCaseResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TestCaseResult(const TestCaseResult& from);
  TestCaseResult(TestCaseResult&& from) noexcept
    : TestCaseResult() {
    *this = ::std::move(from);
  }

  inline TestCaseResult& operator=(const TestCaseResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestCaseResult& operator=(TestCaseResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestCaseResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const TestCaseResult* internal_default_instance() {
    return reinterpret_cast<const TestCaseResult*>(
               &_TestCaseResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(TestCaseResult& a, TestCaseResult& b) {
    a.Swap(&b);
  }
  inline void Swap(TestCaseResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestCaseResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestCaseResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TestCaseResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TestCaseResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TestCaseResult& from) {
    TestCaseResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestCaseResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj_judge.TestCaseResult";
  }
  protected:
  explicit TestCaseResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 2,
    kDiffInfoFieldNumber = 5,
    kIndexFieldNumber = 1,
    kTimeMsFieldNumber = 3,
    kMemoryBytesFieldNumber = 4,
  };
  // string status = 2;
  void clear_status();
  const std::string& status() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status();
  PROTOBUF_NODISCARD std::string* release_status();
  void set_allocated_status(std::string* status);
  private:
  const std::string& _internal_status() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // string diff_info = 5;
  void clear_diff_info();
  const std::string& diff_info() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_diff_info(ArgT0&& arg0, ArgT... args);
  std::string* mutable_diff_info();
  PROTOBUF_NODISCARD std::string* release_diff_info();
  void set_allocated_diff_info(std::string* diff_info);
  private:
  const std::string& _internal_diff_info() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_diff_info(const std::string& value);
  std::string* _internal_mutable_diff_info();
  public:

  // int32 index = 1;
  void clear_index();
  int32_t index() const;
  void set_index(int32_t value);
  private:
  int32_t _internal_index() const;
  void _internal_set_index(int32_t value);
  public:

  // int32 time_ms = 3;
  void clear_time_ms();
  int32_t time_ms() const;
  void set_time_ms(int32_t value);
  private:
  int32_t _internal_time_ms() const;
  void _internal_set_time_ms(int32_t value);
  public:

  // int64 memory_bytes = 4;
  void clear_memory_bytes();
  int64_t memory_bytes() const;
  void set_memory_bytes(int64_t value);
  private:
  int64_t _internal_memory_bytes() const;
  void _internal_set_memory_bytes(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:oj_judge.TestCaseResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr diff_info_;
    int32_t index_;
    int32_t time_ms_;
    int64_t memory_bytes_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_judge_5fservice_2eproto;
};
// -------------------------------------------------------------------

class JudgeResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj_judge.JudgeResult) */ {
 public:
  inline JudgeResult() : JudgeResult(nullptr) {}
  ~JudgeResult() override;
  explicit PROTOBUF_CONSTEXPR JudgeResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JudgeResult(const JudgeResult& from);
  JudgeResult(JudgeResult&& from) noexcept
    : JudgeResult() {
    *this = ::std::move(from);
  }

  inline JudgeResult& operator=(const JudgeResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline JudgeResult& operator=(JudgeResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JudgeResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const JudgeResult* internal_default_instance() {
    return reinterpret_cast<const JudgeResult*>(
               &_JudgeResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(JudgeResult& a, JudgeResult& b) {
    a.Swap(&b);
  }
  inline void Swap(JudgeResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JudgeResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JudgeResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JudgeResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JudgeResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JudgeResult& from) {
    JudgeResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JudgeResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj_judge.JudgeResult";
  }
  protected:
  explicit JudgeResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTestCasesFieldNumber = 6,
    kStatusFieldNumber = 2,
    kCompileErrorFieldNumber = 5,
    kSubmissionIdFieldNumber = 1,
    kTimeUsedMsFieldNumber = 3,
    kMemoryUsedBytesFieldNumber = 4,
  };
  // repeated .oj_judge.TestCaseResult test_cases = 6;
  int test_cases_size() const;
  private:
  int _internal_test_cases_size() const;
  public:
  void clear_test_cases();
  ::oj_judge::TestCaseResult* mutable_test_cases(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj_judge::TestCaseResult >*
      mutable_test_cases();
  private:
  const ::oj_judge::TestCaseResult& _internal_test_cases(int index) const;
  ::oj_judge::TestCaseResult* _internal_add_test_cases();
  public:
  const ::oj_judge::TestCaseResult& test_cases(int index) const;
  ::oj_judge::TestCaseResult* add_test_cases();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj_judge::TestCaseResult >&
      test_cases() const;

  // string status = 2;
  void clear_status();
  const std::string& status() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status();
  PROTOBUF_NODISCARD std::string* release_status();
  void set_allocated_status(std::string* status);
  private:
  const std::string& _internal_status() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // string compile_error = 5;
  void clear_compile_error();
  const std::string& compile_error() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_compile_error(ArgT0&& arg0, ArgT... args);
  std::string* mutable_compile_error();
  PROTOBUF_NODISCARD std::string* release_compile_error();
  void set_allocated_compile_error(std::string* compile_error);
  private:
  const std::string& _internal_compile_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_compile_error(const std::string& value);
  std::string* _internal_mutable_compile_error();
  public:

  // uint32 submission_id = 1;
  void clear_submission_id();
  uint32_t submission_id() const;
  void set_submission_id(uint32_t value);
  private:
  uint32_t _internal_submission_id() const;
  void _internal_set_submission_id(uint32_t value);
  public:

  // int32 time_used_ms = 3;
  void clear_time_used_ms();
  int32_t time_used_ms() const;
  void set_time_used_ms(int32_t value);
  private:
  int32_t _internal_time_used_ms() const;
  void _internal_set_time_used_ms(int32_t value);
  public:

  // int64 memory_used_bytes = 4;
  void clear_memory_used_bytes();
  int64_t memory_used_bytes() const;
  void set_memory_used_bytes(int64_t value);
  private:
  int64_t _internal_memory_used_bytes() const;
  void _internal_set_memory_used_bytes(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:oj_judge.JudgeResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj_judge::TestCaseResult > test_cases_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr compile_error_;
    uint32_t submission_id_;
    int32_t time_used_ms_;
    int64_t memory_used_bytes_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_judge_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetStatusRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj_judge.GetStatusRequest) */ {
 public:
  inline GetStatusRequest() : GetStatusRequest(nullptr) {}
  ~GetStatusRequest() override;
  explicit PROTOBUF_CONSTEXPR GetStatusRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetStatusRequest(const GetStatusRequest& from);
  GetStatusRequest(GetStatusRequest&& from) noexcept
    : GetStatusRequest() {
    *this = ::std::move(from);
  }

  inline GetStatusRequest& operator=(const GetStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetStatusRequest& operator=(GetStatusRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetStatusRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetStatusRequest* internal_default_instance() {
    return reinterpret_cast<const GetStatusRequest*>(
               &_GetStatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(GetStatusRequest& a, GetStatusRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetStatusRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetStatusRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetStatusRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetStatusRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetStatusRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetStatusRequest& from) {
    GetStatusRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetStatusRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj_judge.GetStatusRequest";
  }
  protected:
  explicit GetStatusRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSubmissionIdFieldNumber = 1,
  };
  // uint32 submission_id = 1;
  void clear_submission_id();
  uint32_t submission_id() const;
  void set_submission_id(uint32_t value);
  private:
  uint32_t _internal_submission_id() const;
  void _internal_set_submission_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:oj_judge.GetStatusRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t submission_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_judge_5fservice_2eproto;
};
// ===================================================================

class JudgeService_Stub;

class JudgeService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline JudgeService() {};
 public:
  virtual ~JudgeService();

  typedef JudgeService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void DockerWorkDone(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oj_judge::DockerWorkDoneRequest* request,
                       ::oj_judge::NullRsp* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(JudgeService);
};

class JudgeService_Stub : public JudgeService {
 public:
  JudgeService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  JudgeService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~JudgeService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements JudgeService ------------------------------------------

  void DockerWorkDone(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oj_judge::DockerWorkDoneRequest* request,
                       ::oj_judge::NullRsp* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(JudgeService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SubmitRequest

// uint32 submission_id = 1;
inline void SubmitRequest::clear_submission_id() {
  _impl_.submission_id_ = 0u;
}
inline uint32_t SubmitRequest::_internal_submission_id() const {
  return _impl_.submission_id_;
}
inline uint32_t SubmitRequest::submission_id() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.submission_id)
  return _internal_submission_id();
}
inline void SubmitRequest::_internal_set_submission_id(uint32_t value) {
  
  _impl_.submission_id_ = value;
}
inline void SubmitRequest::set_submission_id(uint32_t value) {
  _internal_set_submission_id(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.submission_id)
}

// string question_id = 2;
inline void SubmitRequest::clear_question_id() {
  _impl_.question_id_.ClearToEmpty();
}
inline const std::string& SubmitRequest::question_id() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.question_id)
  return _internal_question_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubmitRequest::set_question_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.question_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.question_id)
}
inline std::string* SubmitRequest::mutable_question_id() {
  std::string* _s = _internal_mutable_question_id();
  // @@protoc_insertion_point(field_mutable:oj_judge.SubmitRequest.question_id)
  return _s;
}
inline const std::string& SubmitRequest::_internal_question_id() const {
  return _impl_.question_id_.Get();
}
inline void SubmitRequest::_internal_set_question_id(const std::string& value) {
  
  _impl_.question_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SubmitRequest::_internal_mutable_question_id() {
  
  return _impl_.question_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SubmitRequest::release_question_id() {
  // @@protoc_insertion_point(field_release:oj_judge.SubmitRequest.question_id)
  return _impl_.question_id_.Release();
}
inline void SubmitRequest::set_allocated_question_id(std::string* question_id) {
  if (question_id != nullptr) {
    
  } else {
    
  }
  _impl_.question_id_.SetAllocated(question_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.question_id_.IsDefault()) {
    _impl_.question_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.SubmitRequest.question_id)
}

// uint32 user_id = 3;
inline void SubmitRequest::clear_user_id() {
  _impl_.user_id_ = 0u;
}
inline uint32_t SubmitRequest::_internal_user_id() const {
  return _impl_.user_id_;
}
inline uint32_t SubmitRequest::user_id() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.user_id)
  return _internal_user_id();
}
inline void SubmitRequest::_internal_set_user_id(uint32_t value) {
  
  _impl_.user_id_ = value;
}
inline void SubmitRequest::set_user_id(uint32_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.user_id)
}

// string code = 4;
inline void SubmitRequest::clear_code() {
  _impl_.code_.ClearToEmpty();
}
inline const std::string& SubmitRequest::code() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.code)
  return _internal_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubmitRequest::set_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.code)
}
inline std::string* SubmitRequest::mutable_code() {
  std::string* _s = _internal_mutable_code();
  // @@protoc_insertion_point(field_mutable:oj_judge.SubmitRequest.code)
  return _s;
}
inline const std::string& SubmitRequest::_internal_code() const {
  return _impl_.code_.Get();
}
inline void SubmitRequest::_internal_set_code(const std::string& value) {
  
  _impl_.code_.Set(value, GetArenaForAllocation());
}
inline std::string* SubmitRequest::_internal_mutable_code() {
  
  return _impl_.code_.Mutable(GetArenaForAllocation());
}
inline std::string* SubmitRequest::release_code() {
  // @@protoc_insertion_point(field_release:oj_judge.SubmitRequest.code)
  return _impl_.code_.Release();
}
inline void SubmitRequest::set_allocated_code(std::string* code) {
  if (code != nullptr) {
    
  } else {
    
  }
  _impl_.code_.SetAllocated(code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.code_.IsDefault()) {
    _impl_.code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.SubmitRequest.code)
}

// string language = 5;
inline void SubmitRequest::clear_language() {
  _impl_.language_.ClearToEmpty();
}
inline const std::string& SubmitRequest::language() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.language)
  return _internal_language();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubmitRequest::set_language(ArgT0&& arg0, ArgT... args) {
 
 _impl_.language_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.language)
}
inline std::string* SubmitRequest::mutable_language() {
  std::string* _s = _internal_mutable_language();
  // @@protoc_insertion_point(field_mutable:oj_judge.SubmitRequest.language)
  return _s;
}
inline const std::string& SubmitRequest::_internal_language() const {
  return _impl_.language_.Get();
}
inline void SubmitRequest::_internal_set_language(const std::string& value) {
  
  _impl_.language_.Set(value, GetArenaForAllocation());
}
inline std::string* SubmitRequest::_internal_mutable_language() {
  
  return _impl_.language_.Mutable(GetArenaForAllocation());
}
inline std::string* SubmitRequest::release_language() {
  // @@protoc_insertion_point(field_release:oj_judge.SubmitRequest.language)
  return _impl_.language_.Release();
}
inline void SubmitRequest::set_allocated_language(std::string* language) {
  if (language != nullptr) {
    
  } else {
    
  }
  _impl_.language_.SetAllocated(language, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.language_.IsDefault()) {
    _impl_.language_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.SubmitRequest.language)
}

// bool is_custom_test = 6;
inline void SubmitRequest::clear_is_custom_test() {
  _impl_.is_custom_test_ = false;
}
inline bool SubmitRequest::_internal_is_custom_test() const {
  return _impl_.is_custom_test_;
}
inline bool SubmitRequest::is_custom_test() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.is_custom_test)
  return _internal_is_custom_test();
}
inline void SubmitRequest::_internal_set_is_custom_test(bool value) {
  
  _impl_.is_custom_test_ = value;
}
inline void SubmitRequest::set_is_custom_test(bool value) {
  _internal_set_is_custom_test(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.is_custom_test)
}

// string custom_input = 7;
inline void SubmitRequest::clear_custom_input() {
  _impl_.custom_input_.ClearToEmpty();
}
inline const std::string& SubmitRequest::custom_input() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.custom_input)
  return _internal_custom_input();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubmitRequest::set_custom_input(ArgT0&& arg0, ArgT... args) {
 
 _impl_.custom_input_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.custom_input)
}
inline std::string* SubmitRequest::mutable_custom_input() {
  std::string* _s = _internal_mutable_custom_input();
  // @@protoc_insertion_point(field_mutable:oj_judge.SubmitRequest.custom_input)
  return _s;
}
inline const std::string& SubmitRequest::_internal_custom_input() const {
  return _impl_.custom_input_.Get();
}
inline void SubmitRequest::_internal_set_custom_input(const std::string& value) {
  
  _impl_.custom_input_.Set(value, GetArenaForAllocation());
}
inline std::string* SubmitRequest::_internal_mutable_custom_input() {
  
  return _impl_.custom_input_.Mutable(GetArenaForAllocation());
}
inline std::string* SubmitRequest::release_custom_input() {
  // @@protoc_insertion_point(field_release:oj_judge.SubmitRequest.custom_input)
  return _impl_.custom_input_.Release();
}
inline void SubmitRequest::set_allocated_custom_input(std::string* custom_input) {
  if (custom_input != nullptr) {
    
  } else {
    
  }
  _impl_.custom_input_.SetAllocated(custom_input, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.custom_input_.IsDefault()) {
    _impl_.custom_input_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.SubmitRequest.custom_input)
}

// int32 time_limit = 8;
inline void SubmitRequest::clear_time_limit() {
  _impl_.time_limit_ = 0;
}
inline int32_t SubmitRequest::_internal_time_limit() const {
  return _impl_.time_limit_;
}
inline int32_t SubmitRequest::time_limit() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.time_limit)
  return _internal_time_limit();
}
inline void SubmitRequest::_internal_set_time_limit(int32_t value) {
  
  _impl_.time_limit_ = value;
}
inline void SubmitRequest::set_time_limit(int32_t value) {
  _internal_set_time_limit(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.time_limit)
}

// int32 memory_limit = 9;
inline void SubmitRequest::clear_memory_limit() {
  _impl_.memory_limit_ = 0;
}
inline int32_t SubmitRequest::_internal_memory_limit() const {
  return _impl_.memory_limit_;
}
inline int32_t SubmitRequest::memory_limit() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.memory_limit)
  return _internal_memory_limit();
}
inline void SubmitRequest::_internal_set_memory_limit(int32_t value) {
  
  _impl_.memory_limit_ = value;
}
inline void SubmitRequest::set_memory_limit(int32_t value) {
  _internal_set_memory_limit(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.memory_limit)
}

// -------------------------------------------------------------------

// DockerWorkDoneRequest

// string id = 1;
inline void DockerWorkDoneRequest::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& DockerWorkDoneRequest::id() const {
  // @@protoc_insertion_point(field_get:oj_judge.DockerWorkDoneRequest.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DockerWorkDoneRequest::set_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.DockerWorkDoneRequest.id)
}
inline std::string* DockerWorkDoneRequest::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:oj_judge.DockerWorkDoneRequest.id)
  return _s;
}
inline const std::string& DockerWorkDoneRequest::_internal_id() const {
  return _impl_.id_.Get();
}
inline void DockerWorkDoneRequest::_internal_set_id(const std::string& value) {
  
  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* DockerWorkDoneRequest::_internal_mutable_id() {
  
  return _impl_.id_.Mutable(GetArenaForAllocation());
}
inline std::string* DockerWorkDoneRequest::release_id() {
  // @@protoc_insertion_point(field_release:oj_judge.DockerWorkDoneRequest.id)
  return _impl_.id_.Release();
}
inline void DockerWorkDoneRequest::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  _impl_.id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.DockerWorkDoneRequest.id)
}

// -------------------------------------------------------------------

// NullRsp

// -------------------------------------------------------------------

// TestCaseResult

// int32 index = 1;
inline void TestCaseResult::clear_index() {
  _impl_.index_ = 0;
}
inline int32_t TestCaseResult::_internal_index() const {
  return _impl_.index_;
}
inline int32_t TestCaseResult::index() const {
  // @@protoc_insertion_point(field_get:oj_judge.TestCaseResult.index)
  return _internal_index();
}
inline void TestCaseResult::_internal_set_index(int32_t value) {
  
  _impl_.index_ = value;
}
inline void TestCaseResult::set_index(int32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:oj_judge.TestCaseResult.index)
}

// string status = 2;
inline void TestCaseResult::clear_status() {
  _impl_.status_.ClearToEmpty();
}
inline const std::string& TestCaseResult::status() const {
  // @@protoc_insertion_point(field_get:oj_judge.TestCaseResult.status)
  return _internal_status();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TestCaseResult::set_status(ArgT0&& arg0, ArgT... args) {
 
 _impl_.status_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.TestCaseResult.status)
}
inline std::string* TestCaseResult::mutable_status() {
  std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:oj_judge.TestCaseResult.status)
  return _s;
}
inline const std::string& TestCaseResult::_internal_status() const {
  return _impl_.status_.Get();
}
inline void TestCaseResult::_internal_set_status(const std::string& value) {
  
  _impl_.status_.Set(value, GetArenaForAllocation());
}
inline std::string* TestCaseResult::_internal_mutable_status() {
  
  return _impl_.status_.Mutable(GetArenaForAllocation());
}
inline std::string* TestCaseResult::release_status() {
  // @@protoc_insertion_point(field_release:oj_judge.TestCaseResult.status)
  return _impl_.status_.Release();
}
inline void TestCaseResult::set_allocated_status(std::string* status) {
  if (status != nullptr) {
    
  } else {
    
  }
  _impl_.status_.SetAllocated(status, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.TestCaseResult.status)
}

// int32 time_ms = 3;
inline void TestCaseResult::clear_time_ms() {
  _impl_.time_ms_ = 0;
}
inline int32_t TestCaseResult::_internal_time_ms() const {
  return _impl_.time_ms_;
}
inline int32_t TestCaseResult::time_ms() const {
  // @@protoc_insertion_point(field_get:oj_judge.TestCaseResult.time_ms)
  return _internal_time_ms();
}
inline void TestCaseResult::_internal_set_time_ms(int32_t value) {
  
  _impl_.time_ms_ = value;
}
inline void TestCaseResult::set_time_ms(int32_t value) {
  _internal_set_time_ms(value);
  // @@protoc_insertion_point(field_set:oj_judge.TestCaseResult.time_ms)
}

// int64 memory_bytes = 4;
inline void TestCaseResult::clear_memory_bytes() {
  _impl_.memory_bytes_ = int64_t{0};
}
inline int64_t TestCaseResult::_internal_memory_bytes() const {
  return _impl_.memory_bytes_;
}
inline int64_t TestCaseResult::memory_bytes() const {
  // @@protoc_insertion_point(field_get:oj_judge.TestCaseResult.memory_bytes)
  return _internal_memory_bytes();
}
inline void TestCaseResult::_internal_set_memory_bytes(int64_t value) {
  
  _impl_.memory_bytes_ = value;
}
inline void TestCaseResult::set_memory_bytes(int64_t value) {
  _internal_set_memory_bytes(value);
  // @@protoc_insertion_point(field_set:oj_judge.TestCaseResult.memory_bytes)
}

// string diff_info = 5;
inline void TestCaseResult::clear_diff_info() {
  _impl_.diff_info_.ClearToEmpty();
}
inline const std::string& TestCaseResult::diff_info() const {
  // @@protoc_insertion_point(field_get:oj_judge.TestCaseResult.diff_info)
  return _internal_diff_info();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TestCaseResult::set_diff_info(ArgT0&& arg0, ArgT... args) {
 
 _impl_.diff_info_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.TestCaseResult.diff_info)
}
inline std::string* TestCaseResult::mutable_diff_info() {
  std::string* _s = _internal_mutable_diff_info();
  // @@protoc_insertion_point(field_mutable:oj_judge.TestCaseResult.diff_info)
  return _s;
}
inline const std::string& TestCaseResult::_internal_diff_info() const {
  return _impl_.diff_info_.Get();
}
inline void TestCaseResult::_internal_set_diff_info(const std::string& value) {
  
  _impl_.diff_info_.Set(value, GetArenaForAllocation());
}
inline std::string* TestCaseResult::_internal_mutable_diff_info() {
  
  return _impl_.diff_info_.Mutable(GetArenaForAllocation());
}
inline std::string* TestCaseResult::release_diff_info() {
  // @@protoc_insertion_point(field_release:oj_judge.TestCaseResult.diff_info)
  return _impl_.diff_info_.Release();
}
inline void TestCaseResult::set_allocated_diff_info(std::string* diff_info) {
  if (diff_info != nullptr) {
    
  } else {
    
  }
  _impl_.diff_info_.SetAllocated(diff_info, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.diff_info_.IsDefault()) {
    _impl_.diff_info_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.TestCaseResult.diff_info)
}

// -------------------------------------------------------------------

// JudgeResult

// uint32 submission_id = 1;
inline void JudgeResult::clear_submission_id() {
  _impl_.submission_id_ = 0u;
}
inline uint32_t JudgeResult::_internal_submission_id() const {
  return _impl_.submission_id_;
}
inline uint32_t JudgeResult::submission_id() const {
  // @@protoc_insertion_point(field_get:oj_judge.JudgeResult.submission_id)
  return _internal_submission_id();
}
inline void JudgeResult::_internal_set_submission_id(uint32_t value) {
  
  _impl_.submission_id_ = value;
}
inline void JudgeResult::set_submission_id(uint32_t value) {
  _internal_set_submission_id(value);
  // @@protoc_insertion_point(field_set:oj_judge.JudgeResult.submission_id)
}

// string status = 2;
inline void JudgeResult::clear_status() {
  _impl_.status_.ClearToEmpty();
}
inline const std::string& JudgeResult::status() const {
  // @@protoc_insertion_point(field_get:oj_judge.JudgeResult.status)
  return _internal_status();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeResult::set_status(ArgT0&& arg0, ArgT... args) {
 
 _impl_.status_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.JudgeResult.status)
}
inline std::string* JudgeResult::mutable_status() {
  std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:oj_judge.JudgeResult.status)
  return _s;
}
inline const std::string& JudgeResult::_internal_status() const {
  return _impl_.status_.Get();
}
inline void JudgeResult::_internal_set_status(const std::string& value) {
  
  _impl_.status_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeResult::_internal_mutable_status() {
  
  return _impl_.status_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeResult::release_status() {
  // @@protoc_insertion_point(field_release:oj_judge.JudgeResult.status)
  return _impl_.status_.Release();
}
inline void JudgeResult::set_allocated_status(std::string* status) {
  if (status != nullptr) {
    
  } else {
    
  }
  _impl_.status_.SetAllocated(status, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.JudgeResult.status)
}

// int32 time_used_ms = 3;
inline void JudgeResult::clear_time_used_ms() {
  _impl_.time_used_ms_ = 0;
}
inline int32_t JudgeResult::_internal_time_used_ms() const {
  return _impl_.time_used_ms_;
}
inline int32_t JudgeResult::time_used_ms() const {
  // @@protoc_insertion_point(field_get:oj_judge.JudgeResult.time_used_ms)
  return _internal_time_used_ms();
}
inline void JudgeResult::_internal_set_time_used_ms(int32_t value) {
  
  _impl_.time_used_ms_ = value;
}
inline void JudgeResult::set_time_used_ms(int32_t value) {
  _internal_set_time_used_ms(value);
  // @@protoc_insertion_point(field_set:oj_judge.JudgeResult.time_used_ms)
}

// int64 memory_used_bytes = 4;
inline void JudgeResult::clear_memory_used_bytes() {
  _impl_.memory_used_bytes_ = int64_t{0};
}
inline int64_t JudgeResult::_internal_memory_used_bytes() const {
  return _impl_.memory_used_bytes_;
}
inline int64_t JudgeResult::memory_used_bytes() const {
  // @@protoc_insertion_point(field_get:oj_judge.JudgeResult.memory_used_bytes)
  return _internal_memory_used_bytes();
}
inline void JudgeResult::_internal_set_memory_used_bytes(int64_t value) {
  
  _impl_.memory_used_bytes_ = value;
}
inline void JudgeResult::set_memory_used_bytes(int64_t value) {
  _internal_set_memory_used_bytes(value);
  // @@protoc_insertion_point(field_set:oj_judge.JudgeResult.memory_used_bytes)
}

// string compile_error = 5;
inline void JudgeResult::clear_compile_error() {
  _impl_.compile_error_.ClearToEmpty();
}
inline const std::string& JudgeResult::compile_error() const {
  // @@protoc_insertion_point(field_get:oj_judge.JudgeResult.compile_error)
  return _internal_compile_error();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeResult::set_compile_error(ArgT0&& arg0, ArgT... args) {
 
 _impl_.compile_error_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.JudgeResult.compile_error)
}
inline std::string* JudgeResult::mutable_compile_error() {
  std::string* _s = _internal_mutable_compile_error();
  // @@protoc_insertion_point(field_mutable:oj_judge.JudgeResult.compile_error)
  return _s;
}
inline const std::string& JudgeResult::_internal_compile_error() const {
  return _impl_.compile_error_.Get();
}
inline void JudgeResult::_internal_set_compile_error(const std::string& value) {
  
  _impl_.compile_error_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeResult::_internal_mutable_compile_error() {
  
  return _impl_.compile_error_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeResult::release_compile_error() {
  // @@protoc_insertion_point(field_release:oj_judge.JudgeResult.compile_error)
  return _impl_.compile_error_.Release();
}
inline void JudgeResult::set_allocated_compile_error(std::string* compile_error) {
  if (compile_error != nullptr) {
    
  } else {
    
  }
  _impl_.compile_error_.SetAllocated(compile_error, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.compile_error_.IsDefault()) {
    _impl_.compile_error_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.JudgeResult.compile_error)
}

// repeated .oj_judge.TestCaseResult test_cases = 6;
inline int JudgeResult::_internal_test_cases_size() const {
  return _impl_.test_cases_.size();
}
inline int JudgeResult::test_cases_size() const {
  return _internal_test_cases_size();
}
inline void JudgeResult::clear_test_cases() {
  _impl_.test_cases_.Clear();
}
inline ::oj_judge::TestCaseResult* JudgeResult::mutable_test_cases(int index) {
  // @@protoc_insertion_point(field_mutable:oj_judge.JudgeResult.test_cases)
  return _impl_.test_cases_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj_judge::TestCaseResult >*
JudgeResult::mutable_test_cases() {
  // @@protoc_insertion_point(field_mutable_list:oj_judge.JudgeResult.test_cases)
  return &_impl_.test_cases_;
}
inline const ::oj_judge::TestCaseResult& JudgeResult::_internal_test_cases(int index) const {
  return _impl_.test_cases_.Get(index);
}
inline const ::oj_judge::TestCaseResult& JudgeResult::test_cases(int index) const {
  // @@protoc_insertion_point(field_get:oj_judge.JudgeResult.test_cases)
  return _internal_test_cases(index);
}
inline ::oj_judge::TestCaseResult* JudgeResult::_internal_add_test_cases() {
  return _impl_.test_cases_.Add();
}
inline ::oj_judge::TestCaseResult* JudgeResult::add_test_cases() {
  ::oj_judge::TestCaseResult* _add = _internal_add_test_cases();
  // @@protoc_insertion_point(field_add:oj_judge.JudgeResult.test_cases)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj_judge::TestCaseResult >&
JudgeResult::test_cases() const {
  // @@protoc_insertion_point(field_list:oj_judge.JudgeResult.test_cases)
  return _impl_.test_cases_;
}

// -------------------------------------------------------------------

// GetStatusRequest

// uint32 submission_id = 1;
inline void GetStatusRequest::clear_submission_id() {
  _impl_.submission_id_ = 0u;
}
inline uint32_t GetStatusRequest::_internal_submission_id() const {
  return _impl_.submission_id_;
}
inline uint32_t GetStatusRequest::submission_id() const {
  // @@protoc_insertion_point(field_get:oj_judge.GetStatusRequest.submission_id)
  return _internal_submission_id();
}
inline void GetStatusRequest::_internal_set_submission_id(uint32_t value) {
  
  _impl_.submission_id_ = value;
}
inline void GetStatusRequest::set_submission_id(uint32_t value) {
  _internal_set_submission_id(value);
  // @@protoc_insertion_point(field_set:oj_judge.GetStatusRequest.submission_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace oj_judge

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_judge_5fservice_2eproto
