// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: judge_service.proto

#include "judge_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace oj_judge {
PROTOBUF_CONSTEXPR SubmitRequest::SubmitRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.question_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.language_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.custom_input_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.submission_id_)*/0u
  , /*decltype(_impl_.user_id_)*/0u
  , /*decltype(_impl_.is_custom_test_)*/false
  , /*decltype(_impl_.time_limit_)*/0
  , /*decltype(_impl_.memory_limit_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SubmitRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SubmitRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SubmitRequestDefaultTypeInternal() {}
  union {
    SubmitRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SubmitRequestDefaultTypeInternal _SubmitRequest_default_instance_;
PROTOBUF_CONSTEXPR DockerWorkDoneRequest::DockerWorkDoneRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DockerWorkDoneRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DockerWorkDoneRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DockerWorkDoneRequestDefaultTypeInternal() {}
  union {
    DockerWorkDoneRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DockerWorkDoneRequestDefaultTypeInternal _DockerWorkDoneRequest_default_instance_;
PROTOBUF_CONSTEXPR NullRsp::NullRsp(
    ::_pbi::ConstantInitialized) {}
struct NullRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NullRspDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NullRspDefaultTypeInternal() {}
  union {
    NullRsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NullRspDefaultTypeInternal _NullRsp_default_instance_;
PROTOBUF_CONSTEXPR TestCaseResult::TestCaseResult(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.status_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.diff_info_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.index_)*/0
  , /*decltype(_impl_.time_ms_)*/0
  , /*decltype(_impl_.memory_bytes_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TestCaseResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestCaseResultDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestCaseResultDefaultTypeInternal() {}
  union {
    TestCaseResult _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestCaseResultDefaultTypeInternal _TestCaseResult_default_instance_;
PROTOBUF_CONSTEXPR JudgeResult::JudgeResult(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.test_cases_)*/{}
  , /*decltype(_impl_.status_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.compile_error_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.submission_id_)*/0u
  , /*decltype(_impl_.time_used_ms_)*/0
  , /*decltype(_impl_.memory_used_bytes_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct JudgeResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JudgeResultDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~JudgeResultDefaultTypeInternal() {}
  union {
    JudgeResult _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JudgeResultDefaultTypeInternal _JudgeResult_default_instance_;
PROTOBUF_CONSTEXPR GetStatusRequest::GetStatusRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.submission_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetStatusRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetStatusRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetStatusRequestDefaultTypeInternal() {}
  union {
    GetStatusRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetStatusRequestDefaultTypeInternal _GetStatusRequest_default_instance_;
}  // namespace oj_judge
static ::_pb::Metadata file_level_metadata_judge_5fservice_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_judge_5fservice_2eproto = nullptr;
static const ::_pb::ServiceDescriptor* file_level_service_descriptors_judge_5fservice_2eproto[1];

const uint32_t TableStruct_judge_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.submission_id_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.question_id_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.user_id_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.language_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.is_custom_test_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.custom_input_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.time_limit_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.memory_limit_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::oj_judge::DockerWorkDoneRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::oj_judge::DockerWorkDoneRequest, _impl_.id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::oj_judge::NullRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::oj_judge::TestCaseResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::oj_judge::TestCaseResult, _impl_.index_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::TestCaseResult, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::TestCaseResult, _impl_.time_ms_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::TestCaseResult, _impl_.memory_bytes_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::TestCaseResult, _impl_.diff_info_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::oj_judge::JudgeResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::oj_judge::JudgeResult, _impl_.submission_id_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::JudgeResult, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::JudgeResult, _impl_.time_used_ms_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::JudgeResult, _impl_.memory_used_bytes_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::JudgeResult, _impl_.compile_error_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::JudgeResult, _impl_.test_cases_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::oj_judge::GetStatusRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::oj_judge::GetStatusRequest, _impl_.submission_id_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::oj_judge::SubmitRequest)},
  { 15, -1, -1, sizeof(::oj_judge::DockerWorkDoneRequest)},
  { 22, -1, -1, sizeof(::oj_judge::NullRsp)},
  { 28, -1, -1, sizeof(::oj_judge::TestCaseResult)},
  { 39, -1, -1, sizeof(::oj_judge::JudgeResult)},
  { 51, -1, -1, sizeof(::oj_judge::GetStatusRequest)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::oj_judge::_SubmitRequest_default_instance_._instance,
  &::oj_judge::_DockerWorkDoneRequest_default_instance_._instance,
  &::oj_judge::_NullRsp_default_instance_._instance,
  &::oj_judge::_TestCaseResult_default_instance_._instance,
  &::oj_judge::_JudgeResult_default_instance_._instance,
  &::oj_judge::_GetStatusRequest_default_instance_._instance,
};

const char descriptor_table_protodef_judge_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023judge_service.proto\022\010oj_judge\"\304\001\n\rSubm"
  "itRequest\022\025\n\rsubmission_id\030\001 \001(\r\022\023\n\013ques"
  "tion_id\030\002 \001(\t\022\017\n\007user_id\030\003 \001(\r\022\014\n\004code\030\004"
  " \001(\t\022\020\n\010language\030\005 \001(\t\022\026\n\016is_custom_test"
  "\030\006 \001(\010\022\024\n\014custom_input\030\007 \001(\t\022\022\n\ntime_lim"
  "it\030\010 \001(\005\022\024\n\014memory_limit\030\t \001(\005\"#\n\025Docker"
  "WorkDoneRequest\022\n\n\002id\030\001 \001(\t\"\t\n\007NullRsp\"i"
  "\n\016TestCaseResult\022\r\n\005index\030\001 \001(\005\022\016\n\006statu"
  "s\030\002 \001(\t\022\017\n\007time_ms\030\003 \001(\005\022\024\n\014memory_bytes"
  "\030\004 \001(\003\022\021\n\tdiff_info\030\005 \001(\t\"\252\001\n\013JudgeResul"
  "t\022\025\n\rsubmission_id\030\001 \001(\r\022\016\n\006status\030\002 \001(\t"
  "\022\024\n\014time_used_ms\030\003 \001(\005\022\031\n\021memory_used_by"
  "tes\030\004 \001(\003\022\025\n\rcompile_error\030\005 \001(\t\022,\n\ntest"
  "_cases\030\006 \003(\0132\030.oj_judge.TestCaseResult\")"
  "\n\020GetStatusRequest\022\025\n\rsubmission_id\030\001 \001("
  "\r2T\n\014JudgeService\022D\n\016DockerWorkDone\022\037.oj"
  "_judge.DockerWorkDoneRequest\032\021.oj_judge."
  "NullRspB\003\200\001\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_judge_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_judge_5fservice_2eproto = {
    false, false, 700, descriptor_table_protodef_judge_5fservice_2eproto,
    "judge_service.proto",
    &descriptor_table_judge_5fservice_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_judge_5fservice_2eproto::offsets,
    file_level_metadata_judge_5fservice_2eproto, file_level_enum_descriptors_judge_5fservice_2eproto,
    file_level_service_descriptors_judge_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_judge_5fservice_2eproto_getter() {
  return &descriptor_table_judge_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_judge_5fservice_2eproto(&descriptor_table_judge_5fservice_2eproto);
namespace oj_judge {

// ===================================================================

class SubmitRequest::_Internal {
 public:
};

SubmitRequest::SubmitRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:oj_judge.SubmitRequest)
}
SubmitRequest::SubmitRequest(const SubmitRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SubmitRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.question_id_){}
    , decltype(_impl_.code_){}
    , decltype(_impl_.language_){}
    , decltype(_impl_.custom_input_){}
    , decltype(_impl_.submission_id_){}
    , decltype(_impl_.user_id_){}
    , decltype(_impl_.is_custom_test_){}
    , decltype(_impl_.time_limit_){}
    , decltype(_impl_.memory_limit_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.question_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.question_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_question_id().empty()) {
    _this->_impl_.question_id_.Set(from._internal_question_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_code().empty()) {
    _this->_impl_.code_.Set(from._internal_code(), 
      _this->GetArenaForAllocation());
  }
  _impl_.language_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.language_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_language().empty()) {
    _this->_impl_.language_.Set(from._internal_language(), 
      _this->GetArenaForAllocation());
  }
  _impl_.custom_input_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.custom_input_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_custom_input().empty()) {
    _this->_impl_.custom_input_.Set(from._internal_custom_input(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.submission_id_, &from._impl_.submission_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.memory_limit_) -
    reinterpret_cast<char*>(&_impl_.submission_id_)) + sizeof(_impl_.memory_limit_));
  // @@protoc_insertion_point(copy_constructor:oj_judge.SubmitRequest)
}

inline void SubmitRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.question_id_){}
    , decltype(_impl_.code_){}
    , decltype(_impl_.language_){}
    , decltype(_impl_.custom_input_){}
    , decltype(_impl_.submission_id_){0u}
    , decltype(_impl_.user_id_){0u}
    , decltype(_impl_.is_custom_test_){false}
    , decltype(_impl_.time_limit_){0}
    , decltype(_impl_.memory_limit_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.question_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.question_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.language_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.language_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.custom_input_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.custom_input_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SubmitRequest::~SubmitRequest() {
  // @@protoc_insertion_point(destructor:oj_judge.SubmitRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SubmitRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.question_id_.Destroy();
  _impl_.code_.Destroy();
  _impl_.language_.Destroy();
  _impl_.custom_input_.Destroy();
}

void SubmitRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SubmitRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:oj_judge.SubmitRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.question_id_.ClearToEmpty();
  _impl_.code_.ClearToEmpty();
  _impl_.language_.ClearToEmpty();
  _impl_.custom_input_.ClearToEmpty();
  ::memset(&_impl_.submission_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.memory_limit_) -
      reinterpret_cast<char*>(&_impl_.submission_id_)) + sizeof(_impl_.memory_limit_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SubmitRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 submission_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.submission_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string question_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_question_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.SubmitRequest.question_id"));
        } else
          goto handle_unusual;
        continue;
      // uint32 user_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string code = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.SubmitRequest.code"));
        } else
          goto handle_unusual;
        continue;
      // string language = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_language();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.SubmitRequest.language"));
        } else
          goto handle_unusual;
        continue;
      // bool is_custom_test = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.is_custom_test_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string custom_input = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_custom_input();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.SubmitRequest.custom_input"));
        } else
          goto handle_unusual;
        continue;
      // int32 time_limit = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.time_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 memory_limit = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.memory_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SubmitRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:oj_judge.SubmitRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 submission_id = 1;
  if (this->_internal_submission_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_submission_id(), target);
  }

  // string question_id = 2;
  if (!this->_internal_question_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_question_id().data(), static_cast<int>(this->_internal_question_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.SubmitRequest.question_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_question_id(), target);
  }

  // uint32 user_id = 3;
  if (this->_internal_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_user_id(), target);
  }

  // string code = 4;
  if (!this->_internal_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_code().data(), static_cast<int>(this->_internal_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.SubmitRequest.code");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_code(), target);
  }

  // string language = 5;
  if (!this->_internal_language().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_language().data(), static_cast<int>(this->_internal_language().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.SubmitRequest.language");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_language(), target);
  }

  // bool is_custom_test = 6;
  if (this->_internal_is_custom_test() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(6, this->_internal_is_custom_test(), target);
  }

  // string custom_input = 7;
  if (!this->_internal_custom_input().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_custom_input().data(), static_cast<int>(this->_internal_custom_input().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.SubmitRequest.custom_input");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_custom_input(), target);
  }

  // int32 time_limit = 8;
  if (this->_internal_time_limit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(8, this->_internal_time_limit(), target);
  }

  // int32 memory_limit = 9;
  if (this->_internal_memory_limit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(9, this->_internal_memory_limit(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oj_judge.SubmitRequest)
  return target;
}

size_t SubmitRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oj_judge.SubmitRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string question_id = 2;
  if (!this->_internal_question_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_question_id());
  }

  // string code = 4;
  if (!this->_internal_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_code());
  }

  // string language = 5;
  if (!this->_internal_language().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_language());
  }

  // string custom_input = 7;
  if (!this->_internal_custom_input().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_custom_input());
  }

  // uint32 submission_id = 1;
  if (this->_internal_submission_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_submission_id());
  }

  // uint32 user_id = 3;
  if (this->_internal_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_user_id());
  }

  // bool is_custom_test = 6;
  if (this->_internal_is_custom_test() != 0) {
    total_size += 1 + 1;
  }

  // int32 time_limit = 8;
  if (this->_internal_time_limit() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_time_limit());
  }

  // int32 memory_limit = 9;
  if (this->_internal_memory_limit() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_memory_limit());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SubmitRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SubmitRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SubmitRequest::GetClassData() const { return &_class_data_; }


void SubmitRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SubmitRequest*>(&to_msg);
  auto& from = static_cast<const SubmitRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:oj_judge.SubmitRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_question_id().empty()) {
    _this->_internal_set_question_id(from._internal_question_id());
  }
  if (!from._internal_code().empty()) {
    _this->_internal_set_code(from._internal_code());
  }
  if (!from._internal_language().empty()) {
    _this->_internal_set_language(from._internal_language());
  }
  if (!from._internal_custom_input().empty()) {
    _this->_internal_set_custom_input(from._internal_custom_input());
  }
  if (from._internal_submission_id() != 0) {
    _this->_internal_set_submission_id(from._internal_submission_id());
  }
  if (from._internal_user_id() != 0) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (from._internal_is_custom_test() != 0) {
    _this->_internal_set_is_custom_test(from._internal_is_custom_test());
  }
  if (from._internal_time_limit() != 0) {
    _this->_internal_set_time_limit(from._internal_time_limit());
  }
  if (from._internal_memory_limit() != 0) {
    _this->_internal_set_memory_limit(from._internal_memory_limit());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SubmitRequest::CopyFrom(const SubmitRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oj_judge.SubmitRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SubmitRequest::IsInitialized() const {
  return true;
}

void SubmitRequest::InternalSwap(SubmitRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.question_id_, lhs_arena,
      &other->_impl_.question_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.code_, lhs_arena,
      &other->_impl_.code_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.language_, lhs_arena,
      &other->_impl_.language_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.custom_input_, lhs_arena,
      &other->_impl_.custom_input_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SubmitRequest, _impl_.memory_limit_)
      + sizeof(SubmitRequest::_impl_.memory_limit_)
      - PROTOBUF_FIELD_OFFSET(SubmitRequest, _impl_.submission_id_)>(
          reinterpret_cast<char*>(&_impl_.submission_id_),
          reinterpret_cast<char*>(&other->_impl_.submission_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SubmitRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_judge_5fservice_2eproto_getter, &descriptor_table_judge_5fservice_2eproto_once,
      file_level_metadata_judge_5fservice_2eproto[0]);
}

// ===================================================================

class DockerWorkDoneRequest::_Internal {
 public:
};

DockerWorkDoneRequest::DockerWorkDoneRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:oj_judge.DockerWorkDoneRequest)
}
DockerWorkDoneRequest::DockerWorkDoneRequest(const DockerWorkDoneRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DockerWorkDoneRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_id().empty()) {
    _this->_impl_.id_.Set(from._internal_id(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:oj_judge.DockerWorkDoneRequest)
}

inline void DockerWorkDoneRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DockerWorkDoneRequest::~DockerWorkDoneRequest() {
  // @@protoc_insertion_point(destructor:oj_judge.DockerWorkDoneRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DockerWorkDoneRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.id_.Destroy();
}

void DockerWorkDoneRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DockerWorkDoneRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:oj_judge.DockerWorkDoneRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DockerWorkDoneRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.DockerWorkDoneRequest.id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DockerWorkDoneRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:oj_judge.DockerWorkDoneRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.DockerWorkDoneRequest.id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oj_judge.DockerWorkDoneRequest)
  return target;
}

size_t DockerWorkDoneRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oj_judge.DockerWorkDoneRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DockerWorkDoneRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DockerWorkDoneRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DockerWorkDoneRequest::GetClassData() const { return &_class_data_; }


void DockerWorkDoneRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DockerWorkDoneRequest*>(&to_msg);
  auto& from = static_cast<const DockerWorkDoneRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:oj_judge.DockerWorkDoneRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DockerWorkDoneRequest::CopyFrom(const DockerWorkDoneRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oj_judge.DockerWorkDoneRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DockerWorkDoneRequest::IsInitialized() const {
  return true;
}

void DockerWorkDoneRequest::InternalSwap(DockerWorkDoneRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.id_, lhs_arena,
      &other->_impl_.id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata DockerWorkDoneRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_judge_5fservice_2eproto_getter, &descriptor_table_judge_5fservice_2eproto_once,
      file_level_metadata_judge_5fservice_2eproto[1]);
}

// ===================================================================

class NullRsp::_Internal {
 public:
};

NullRsp::NullRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:oj_judge.NullRsp)
}
NullRsp::NullRsp(const NullRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  NullRsp* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:oj_judge.NullRsp)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NullRsp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NullRsp::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata NullRsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_judge_5fservice_2eproto_getter, &descriptor_table_judge_5fservice_2eproto_once,
      file_level_metadata_judge_5fservice_2eproto[2]);
}

// ===================================================================

class TestCaseResult::_Internal {
 public:
};

TestCaseResult::TestCaseResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:oj_judge.TestCaseResult)
}
TestCaseResult::TestCaseResult(const TestCaseResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TestCaseResult* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){}
    , decltype(_impl_.diff_info_){}
    , decltype(_impl_.index_){}
    , decltype(_impl_.time_ms_){}
    , decltype(_impl_.memory_bytes_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.status_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_status().empty()) {
    _this->_impl_.status_.Set(from._internal_status(), 
      _this->GetArenaForAllocation());
  }
  _impl_.diff_info_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.diff_info_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_diff_info().empty()) {
    _this->_impl_.diff_info_.Set(from._internal_diff_info(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.index_, &from._impl_.index_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.memory_bytes_) -
    reinterpret_cast<char*>(&_impl_.index_)) + sizeof(_impl_.memory_bytes_));
  // @@protoc_insertion_point(copy_constructor:oj_judge.TestCaseResult)
}

inline void TestCaseResult::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){}
    , decltype(_impl_.diff_info_){}
    , decltype(_impl_.index_){0}
    , decltype(_impl_.time_ms_){0}
    , decltype(_impl_.memory_bytes_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.status_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.diff_info_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.diff_info_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TestCaseResult::~TestCaseResult() {
  // @@protoc_insertion_point(destructor:oj_judge.TestCaseResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TestCaseResult::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.status_.Destroy();
  _impl_.diff_info_.Destroy();
}

void TestCaseResult::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TestCaseResult::Clear() {
// @@protoc_insertion_point(message_clear_start:oj_judge.TestCaseResult)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_.ClearToEmpty();
  _impl_.diff_info_.ClearToEmpty();
  ::memset(&_impl_.index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.memory_bytes_) -
      reinterpret_cast<char*>(&_impl_.index_)) + sizeof(_impl_.memory_bytes_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TestCaseResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 index = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string status = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_status();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.TestCaseResult.status"));
        } else
          goto handle_unusual;
        continue;
      // int32 time_ms = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.time_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 memory_bytes = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.memory_bytes_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string diff_info = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_diff_info();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.TestCaseResult.diff_info"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TestCaseResult::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:oj_judge.TestCaseResult)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 index = 1;
  if (this->_internal_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_index(), target);
  }

  // string status = 2;
  if (!this->_internal_status().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_status().data(), static_cast<int>(this->_internal_status().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.TestCaseResult.status");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_status(), target);
  }

  // int32 time_ms = 3;
  if (this->_internal_time_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_time_ms(), target);
  }

  // int64 memory_bytes = 4;
  if (this->_internal_memory_bytes() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_memory_bytes(), target);
  }

  // string diff_info = 5;
  if (!this->_internal_diff_info().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_diff_info().data(), static_cast<int>(this->_internal_diff_info().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.TestCaseResult.diff_info");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_diff_info(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oj_judge.TestCaseResult)
  return target;
}

size_t TestCaseResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oj_judge.TestCaseResult)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string status = 2;
  if (!this->_internal_status().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_status());
  }

  // string diff_info = 5;
  if (!this->_internal_diff_info().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_diff_info());
  }

  // int32 index = 1;
  if (this->_internal_index() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_index());
  }

  // int32 time_ms = 3;
  if (this->_internal_time_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_time_ms());
  }

  // int64 memory_bytes = 4;
  if (this->_internal_memory_bytes() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_memory_bytes());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TestCaseResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TestCaseResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TestCaseResult::GetClassData() const { return &_class_data_; }


void TestCaseResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TestCaseResult*>(&to_msg);
  auto& from = static_cast<const TestCaseResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:oj_judge.TestCaseResult)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_status().empty()) {
    _this->_internal_set_status(from._internal_status());
  }
  if (!from._internal_diff_info().empty()) {
    _this->_internal_set_diff_info(from._internal_diff_info());
  }
  if (from._internal_index() != 0) {
    _this->_internal_set_index(from._internal_index());
  }
  if (from._internal_time_ms() != 0) {
    _this->_internal_set_time_ms(from._internal_time_ms());
  }
  if (from._internal_memory_bytes() != 0) {
    _this->_internal_set_memory_bytes(from._internal_memory_bytes());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TestCaseResult::CopyFrom(const TestCaseResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oj_judge.TestCaseResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestCaseResult::IsInitialized() const {
  return true;
}

void TestCaseResult::InternalSwap(TestCaseResult* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.status_, lhs_arena,
      &other->_impl_.status_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.diff_info_, lhs_arena,
      &other->_impl_.diff_info_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TestCaseResult, _impl_.memory_bytes_)
      + sizeof(TestCaseResult::_impl_.memory_bytes_)
      - PROTOBUF_FIELD_OFFSET(TestCaseResult, _impl_.index_)>(
          reinterpret_cast<char*>(&_impl_.index_),
          reinterpret_cast<char*>(&other->_impl_.index_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TestCaseResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_judge_5fservice_2eproto_getter, &descriptor_table_judge_5fservice_2eproto_once,
      file_level_metadata_judge_5fservice_2eproto[3]);
}

// ===================================================================

class JudgeResult::_Internal {
 public:
};

JudgeResult::JudgeResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:oj_judge.JudgeResult)
}
JudgeResult::JudgeResult(const JudgeResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  JudgeResult* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.test_cases_){from._impl_.test_cases_}
    , decltype(_impl_.status_){}
    , decltype(_impl_.compile_error_){}
    , decltype(_impl_.submission_id_){}
    , decltype(_impl_.time_used_ms_){}
    , decltype(_impl_.memory_used_bytes_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.status_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_status().empty()) {
    _this->_impl_.status_.Set(from._internal_status(), 
      _this->GetArenaForAllocation());
  }
  _impl_.compile_error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.compile_error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_compile_error().empty()) {
    _this->_impl_.compile_error_.Set(from._internal_compile_error(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.submission_id_, &from._impl_.submission_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.memory_used_bytes_) -
    reinterpret_cast<char*>(&_impl_.submission_id_)) + sizeof(_impl_.memory_used_bytes_));
  // @@protoc_insertion_point(copy_constructor:oj_judge.JudgeResult)
}

inline void JudgeResult::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.test_cases_){arena}
    , decltype(_impl_.status_){}
    , decltype(_impl_.compile_error_){}
    , decltype(_impl_.submission_id_){0u}
    , decltype(_impl_.time_used_ms_){0}
    , decltype(_impl_.memory_used_bytes_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.status_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.compile_error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.compile_error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

JudgeResult::~JudgeResult() {
  // @@protoc_insertion_point(destructor:oj_judge.JudgeResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void JudgeResult::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.test_cases_.~RepeatedPtrField();
  _impl_.status_.Destroy();
  _impl_.compile_error_.Destroy();
}

void JudgeResult::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void JudgeResult::Clear() {
// @@protoc_insertion_point(message_clear_start:oj_judge.JudgeResult)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.test_cases_.Clear();
  _impl_.status_.ClearToEmpty();
  _impl_.compile_error_.ClearToEmpty();
  ::memset(&_impl_.submission_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.memory_used_bytes_) -
      reinterpret_cast<char*>(&_impl_.submission_id_)) + sizeof(_impl_.memory_used_bytes_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* JudgeResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 submission_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.submission_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string status = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_status();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.JudgeResult.status"));
        } else
          goto handle_unusual;
        continue;
      // int32 time_used_ms = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.time_used_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 memory_used_bytes = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.memory_used_bytes_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string compile_error = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_compile_error();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.JudgeResult.compile_error"));
        } else
          goto handle_unusual;
        continue;
      // repeated .oj_judge.TestCaseResult test_cases = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_test_cases(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* JudgeResult::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:oj_judge.JudgeResult)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 submission_id = 1;
  if (this->_internal_submission_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_submission_id(), target);
  }

  // string status = 2;
  if (!this->_internal_status().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_status().data(), static_cast<int>(this->_internal_status().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.JudgeResult.status");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_status(), target);
  }

  // int32 time_used_ms = 3;
  if (this->_internal_time_used_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_time_used_ms(), target);
  }

  // int64 memory_used_bytes = 4;
  if (this->_internal_memory_used_bytes() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_memory_used_bytes(), target);
  }

  // string compile_error = 5;
  if (!this->_internal_compile_error().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_compile_error().data(), static_cast<int>(this->_internal_compile_error().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.JudgeResult.compile_error");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_compile_error(), target);
  }

  // repeated .oj_judge.TestCaseResult test_cases = 6;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_test_cases_size()); i < n; i++) {
    const auto& repfield = this->_internal_test_cases(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(6, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oj_judge.JudgeResult)
  return target;
}

size_t JudgeResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oj_judge.JudgeResult)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .oj_judge.TestCaseResult test_cases = 6;
  total_size += 1UL * this->_internal_test_cases_size();
  for (const auto& msg : this->_impl_.test_cases_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string status = 2;
  if (!this->_internal_status().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_status());
  }

  // string compile_error = 5;
  if (!this->_internal_compile_error().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_compile_error());
  }

  // uint32 submission_id = 1;
  if (this->_internal_submission_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_submission_id());
  }

  // int32 time_used_ms = 3;
  if (this->_internal_time_used_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_time_used_ms());
  }

  // int64 memory_used_bytes = 4;
  if (this->_internal_memory_used_bytes() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_memory_used_bytes());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData JudgeResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    JudgeResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*JudgeResult::GetClassData() const { return &_class_data_; }


void JudgeResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<JudgeResult*>(&to_msg);
  auto& from = static_cast<const JudgeResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:oj_judge.JudgeResult)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.test_cases_.MergeFrom(from._impl_.test_cases_);
  if (!from._internal_status().empty()) {
    _this->_internal_set_status(from._internal_status());
  }
  if (!from._internal_compile_error().empty()) {
    _this->_internal_set_compile_error(from._internal_compile_error());
  }
  if (from._internal_submission_id() != 0) {
    _this->_internal_set_submission_id(from._internal_submission_id());
  }
  if (from._internal_time_used_ms() != 0) {
    _this->_internal_set_time_used_ms(from._internal_time_used_ms());
  }
  if (from._internal_memory_used_bytes() != 0) {
    _this->_internal_set_memory_used_bytes(from._internal_memory_used_bytes());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void JudgeResult::CopyFrom(const JudgeResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oj_judge.JudgeResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JudgeResult::IsInitialized() const {
  return true;
}

void JudgeResult::InternalSwap(JudgeResult* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.test_cases_.InternalSwap(&other->_impl_.test_cases_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.status_, lhs_arena,
      &other->_impl_.status_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.compile_error_, lhs_arena,
      &other->_impl_.compile_error_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(JudgeResult, _impl_.memory_used_bytes_)
      + sizeof(JudgeResult::_impl_.memory_used_bytes_)
      - PROTOBUF_FIELD_OFFSET(JudgeResult, _impl_.submission_id_)>(
          reinterpret_cast<char*>(&_impl_.submission_id_),
          reinterpret_cast<char*>(&other->_impl_.submission_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata JudgeResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_judge_5fservice_2eproto_getter, &descriptor_table_judge_5fservice_2eproto_once,
      file_level_metadata_judge_5fservice_2eproto[4]);
}

// ===================================================================

class GetStatusRequest::_Internal {
 public:
};

GetStatusRequest::GetStatusRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:oj_judge.GetStatusRequest)
}
GetStatusRequest::GetStatusRequest(const GetStatusRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetStatusRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.submission_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.submission_id_ = from._impl_.submission_id_;
  // @@protoc_insertion_point(copy_constructor:oj_judge.GetStatusRequest)
}

inline void GetStatusRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.submission_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetStatusRequest::~GetStatusRequest() {
  // @@protoc_insertion_point(destructor:oj_judge.GetStatusRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetStatusRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GetStatusRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetStatusRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:oj_judge.GetStatusRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.submission_id_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetStatusRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 submission_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.submission_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetStatusRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:oj_judge.GetStatusRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 submission_id = 1;
  if (this->_internal_submission_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_submission_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oj_judge.GetStatusRequest)
  return target;
}

size_t GetStatusRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oj_judge.GetStatusRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 submission_id = 1;
  if (this->_internal_submission_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_submission_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetStatusRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetStatusRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetStatusRequest::GetClassData() const { return &_class_data_; }


void GetStatusRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetStatusRequest*>(&to_msg);
  auto& from = static_cast<const GetStatusRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:oj_judge.GetStatusRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_submission_id() != 0) {
    _this->_internal_set_submission_id(from._internal_submission_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetStatusRequest::CopyFrom(const GetStatusRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oj_judge.GetStatusRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetStatusRequest::IsInitialized() const {
  return true;
}

void GetStatusRequest::InternalSwap(GetStatusRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.submission_id_, other->_impl_.submission_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetStatusRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_judge_5fservice_2eproto_getter, &descriptor_table_judge_5fservice_2eproto_once,
      file_level_metadata_judge_5fservice_2eproto[5]);
}

// ===================================================================

JudgeService::~JudgeService() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* JudgeService::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_judge_5fservice_2eproto);
  return file_level_service_descriptors_judge_5fservice_2eproto[0];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* JudgeService::GetDescriptor() {
  return descriptor();
}

void JudgeService::DockerWorkDone(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::oj_judge::DockerWorkDoneRequest*,
                         ::oj_judge::NullRsp*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method DockerWorkDone() not implemented.");
  done->Run();
}

void JudgeService::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_judge_5fservice_2eproto[0]);
  switch(method->index()) {
    case 0:
      DockerWorkDone(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::oj_judge::DockerWorkDoneRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::oj_judge::NullRsp*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& JudgeService::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::oj_judge::DockerWorkDoneRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& JudgeService::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::oj_judge::NullRsp::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

JudgeService_Stub::JudgeService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
JudgeService_Stub::JudgeService_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
JudgeService_Stub::~JudgeService_Stub() {
  if (owns_channel_) delete channel_;
}

void JudgeService_Stub::DockerWorkDone(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::oj_judge::DockerWorkDoneRequest* request,
                              ::oj_judge::NullRsp* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace oj_judge
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::oj_judge::SubmitRequest*
Arena::CreateMaybeMessage< ::oj_judge::SubmitRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::oj_judge::SubmitRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::oj_judge::DockerWorkDoneRequest*
Arena::CreateMaybeMessage< ::oj_judge::DockerWorkDoneRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::oj_judge::DockerWorkDoneRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::oj_judge::NullRsp*
Arena::CreateMaybeMessage< ::oj_judge::NullRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::oj_judge::NullRsp >(arena);
}
template<> PROTOBUF_NOINLINE ::oj_judge::TestCaseResult*
Arena::CreateMaybeMessage< ::oj_judge::TestCaseResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::oj_judge::TestCaseResult >(arena);
}
template<> PROTOBUF_NOINLINE ::oj_judge::JudgeResult*
Arena::CreateMaybeMessage< ::oj_judge::JudgeResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::oj_judge::JudgeResult >(arena);
}
template<> PROTOBUF_NOINLINE ::oj_judge::GetStatusRequest*
Arena::CreateMaybeMessage< ::oj_judge::GetStatusRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::oj_judge::GetStatusRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
