// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: judge_service.proto

#include "judge_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace oj_judge {
PROTOBUF_CONSTEXPR SubmitRequest::SubmitRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.question_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.language_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.custom_input_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.submission_id_)*/0u
  , /*decltype(_impl_.user_id_)*/0u
  , /*decltype(_impl_.timestamp_)*/uint64_t{0u}
  , /*decltype(_impl_.time_limit_)*/0
  , /*decltype(_impl_.memory_limit_)*/0
  , /*decltype(_impl_.is_custom_test_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SubmitRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SubmitRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SubmitRequestDefaultTypeInternal() {}
  union {
    SubmitRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SubmitRequestDefaultTypeInternal _SubmitRequest_default_instance_;
PROTOBUF_CONSTEXPR SubmitStatus::SubmitStatus(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.time_cost_)*/0
  , /*decltype(_impl_.memory_cost_)*/0
  , /*decltype(_impl_.result_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SubmitStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SubmitStatusDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SubmitStatusDefaultTypeInternal() {}
  union {
    SubmitStatus _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SubmitStatusDefaultTypeInternal _SubmitStatus_default_instance_;
PROTOBUF_CONSTEXPR JudgeFinishedRequest::JudgeFinishedRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.status_list_)*/{}
  , /*decltype(_impl_.question_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.submission_id_)*/0u
  , /*decltype(_impl_.user_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct JudgeFinishedRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JudgeFinishedRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~JudgeFinishedRequestDefaultTypeInternal() {}
  union {
    JudgeFinishedRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JudgeFinishedRequestDefaultTypeInternal _JudgeFinishedRequest_default_instance_;
PROTOBUF_CONSTEXPR DockerWorkDoneRequest::DockerWorkDoneRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.status_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.exit_code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DockerWorkDoneRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DockerWorkDoneRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DockerWorkDoneRequestDefaultTypeInternal() {}
  union {
    DockerWorkDoneRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DockerWorkDoneRequestDefaultTypeInternal _DockerWorkDoneRequest_default_instance_;
PROTOBUF_CONSTEXPR NullRsp::NullRsp(
    ::_pbi::ConstantInitialized) {}
struct NullRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NullRspDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NullRspDefaultTypeInternal() {}
  union {
    NullRsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NullRspDefaultTypeInternal _NullRsp_default_instance_;
}  // namespace oj_judge
static ::_pb::Metadata file_level_metadata_judge_5fservice_2eproto[5];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_judge_5fservice_2eproto[1];
static const ::_pb::ServiceDescriptor* file_level_service_descriptors_judge_5fservice_2eproto[1];

const uint32_t TableStruct_judge_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.submission_id_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.question_id_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.user_id_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.language_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.time_limit_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.memory_limit_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.is_custom_test_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitRequest, _impl_.custom_input_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitStatus, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitStatus, _impl_.time_cost_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitStatus, _impl_.memory_cost_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::SubmitStatus, _impl_.result_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::oj_judge::JudgeFinishedRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::oj_judge::JudgeFinishedRequest, _impl_.submission_id_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::JudgeFinishedRequest, _impl_.question_id_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::JudgeFinishedRequest, _impl_.user_id_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::JudgeFinishedRequest, _impl_.status_list_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::oj_judge::DockerWorkDoneRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::oj_judge::DockerWorkDoneRequest, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::DockerWorkDoneRequest, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::oj_judge::DockerWorkDoneRequest, _impl_.exit_code_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::oj_judge::NullRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::oj_judge::SubmitRequest)},
  { 16, -1, -1, sizeof(::oj_judge::SubmitStatus)},
  { 25, -1, -1, sizeof(::oj_judge::JudgeFinishedRequest)},
  { 35, -1, -1, sizeof(::oj_judge::DockerWorkDoneRequest)},
  { 44, -1, -1, sizeof(::oj_judge::NullRsp)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::oj_judge::_SubmitRequest_default_instance_._instance,
  &::oj_judge::_SubmitStatus_default_instance_._instance,
  &::oj_judge::_JudgeFinishedRequest_default_instance_._instance,
  &::oj_judge::_DockerWorkDoneRequest_default_instance_._instance,
  &::oj_judge::_NullRsp_default_instance_._instance,
};

const char descriptor_table_protodef_judge_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023judge_service.proto\022\010oj_judge\"\327\001\n\rSubm"
  "itRequest\022\025\n\rsubmission_id\030\001 \001(\r\022\023\n\013ques"
  "tion_id\030\002 \001(\t\022\017\n\007user_id\030\003 \001(\r\022\014\n\004code\030\004"
  " \001(\t\022\021\n\ttimestamp\030\005 \001(\004\022\020\n\010language\030\006 \001("
  "\t\022\022\n\ntime_limit\030\007 \001(\005\022\024\n\014memory_limit\030\010 "
  "\001(\005\022\026\n\016is_custom_test\030\t \001(\010\022\024\n\014custom_in"
  "put\030\n \001(\t\"^\n\014SubmitStatus\022\021\n\ttime_cost\030\001"
  " \001(\005\022\023\n\013memory_cost\030\002 \001(\005\022&\n\006result\030\003 \001("
  "\0162\026.oj_judge.SubmitResult\"\200\001\n\024JudgeFinis"
  "hedRequest\022\025\n\rsubmission_id\030\001 \001(\r\022\023\n\013que"
  "stion_id\030\002 \001(\t\022\017\n\007user_id\030\003 \001(\r\022+\n\013statu"
  "s_list\030\004 \003(\0132\026.oj_judge.SubmitStatus\"F\n\025"
  "DockerWorkDoneRequest\022\n\n\002id\030\001 \001(\t\022\016\n\006sta"
  "tus\030\002 \001(\t\022\021\n\texit_code\030\003 \001(\005\"\t\n\007NullRsp*"
  "\222\001\n\014SubmitResult\022\006\n\002AC\020\000\022\006\n\002WA\020\001\022\021\n\rCOMP"
  "ILE_ERROR\020\002\022\020\n\014MEMORY_LIMIT\020\003\022\016\n\nTIME_LI"
  "MIT\020\004\022\016\n\nSEGV_ERROR\020\005\022\r\n\tFPE_ERROR\020\006\022\021\n\r"
  "RUNTIME_ERROR\020\007\022\013\n\007UNKNOWN\020\0102T\n\014JudgeSer"
  "vice\022D\n\016DockerWorkDone\022\037.oj_judge.Docker"
  "WorkDoneRequest\032\021.oj_judge.NullRspB\003\200\001\001b"
  "\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_judge_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_judge_5fservice_2eproto = {
    false, false, 807, descriptor_table_protodef_judge_5fservice_2eproto,
    "judge_service.proto",
    &descriptor_table_judge_5fservice_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_judge_5fservice_2eproto::offsets,
    file_level_metadata_judge_5fservice_2eproto, file_level_enum_descriptors_judge_5fservice_2eproto,
    file_level_service_descriptors_judge_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_judge_5fservice_2eproto_getter() {
  return &descriptor_table_judge_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_judge_5fservice_2eproto(&descriptor_table_judge_5fservice_2eproto);
namespace oj_judge {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SubmitResult_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_judge_5fservice_2eproto);
  return file_level_enum_descriptors_judge_5fservice_2eproto[0];
}
bool SubmitResult_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class SubmitRequest::_Internal {
 public:
};

SubmitRequest::SubmitRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:oj_judge.SubmitRequest)
}
SubmitRequest::SubmitRequest(const SubmitRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SubmitRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.question_id_){}
    , decltype(_impl_.code_){}
    , decltype(_impl_.language_){}
    , decltype(_impl_.custom_input_){}
    , decltype(_impl_.submission_id_){}
    , decltype(_impl_.user_id_){}
    , decltype(_impl_.timestamp_){}
    , decltype(_impl_.time_limit_){}
    , decltype(_impl_.memory_limit_){}
    , decltype(_impl_.is_custom_test_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.question_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.question_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_question_id().empty()) {
    _this->_impl_.question_id_.Set(from._internal_question_id(),
      _this->GetArenaForAllocation());
  }
  _impl_.code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_code().empty()) {
    _this->_impl_.code_.Set(from._internal_code(),
      _this->GetArenaForAllocation());
  }
  _impl_.language_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.language_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_language().empty()) {
    _this->_impl_.language_.Set(from._internal_language(),
      _this->GetArenaForAllocation());
  }
  _impl_.custom_input_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.custom_input_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_custom_input().empty()) {
    _this->_impl_.custom_input_.Set(from._internal_custom_input(),
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.submission_id_, &from._impl_.submission_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_custom_test_) -
    reinterpret_cast<char*>(&_impl_.submission_id_)) + sizeof(_impl_.is_custom_test_));
  // @@protoc_insertion_point(copy_constructor:oj_judge.SubmitRequest)
}

inline void SubmitRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.question_id_){}
    , decltype(_impl_.code_){}
    , decltype(_impl_.language_){}
    , decltype(_impl_.custom_input_){}
    , decltype(_impl_.submission_id_){0u}
    , decltype(_impl_.user_id_){0u}
    , decltype(_impl_.timestamp_){uint64_t{0u}}
    , decltype(_impl_.time_limit_){0}
    , decltype(_impl_.memory_limit_){0}
    , decltype(_impl_.is_custom_test_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.question_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.question_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.language_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.language_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.custom_input_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.custom_input_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SubmitRequest::~SubmitRequest() {
  // @@protoc_insertion_point(destructor:oj_judge.SubmitRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SubmitRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.question_id_.Destroy();
  _impl_.code_.Destroy();
  _impl_.language_.Destroy();
  _impl_.custom_input_.Destroy();
}

void SubmitRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SubmitRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:oj_judge.SubmitRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.question_id_.ClearToEmpty();
  _impl_.code_.ClearToEmpty();
  _impl_.language_.ClearToEmpty();
  _impl_.custom_input_.ClearToEmpty();
  ::memset(&_impl_.submission_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_custom_test_) -
      reinterpret_cast<char*>(&_impl_.submission_id_)) + sizeof(_impl_.is_custom_test_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SubmitRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 submission_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.submission_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string question_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_question_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.SubmitRequest.question_id"));
        } else
          goto handle_unusual;
        continue;
      // uint32 user_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string code = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.SubmitRequest.code"));
        } else
          goto handle_unusual;
        continue;
      // uint64 timestamp = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string language = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_language();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.SubmitRequest.language"));
        } else
          goto handle_unusual;
        continue;
      // int32 time_limit = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.time_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 memory_limit = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.memory_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_custom_test = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.is_custom_test_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string custom_input = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_custom_input();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.SubmitRequest.custom_input"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SubmitRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:oj_judge.SubmitRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 submission_id = 1;
  if (this->_internal_submission_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_submission_id(), target);
  }

  // string question_id = 2;
  if (!this->_internal_question_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_question_id().data(), static_cast<int>(this->_internal_question_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.SubmitRequest.question_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_question_id(), target);
  }

  // uint32 user_id = 3;
  if (this->_internal_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_user_id(), target);
  }

  // string code = 4;
  if (!this->_internal_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_code().data(), static_cast<int>(this->_internal_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.SubmitRequest.code");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_code(), target);
  }

  // uint64 timestamp = 5;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_timestamp(), target);
  }

  // string language = 6;
  if (!this->_internal_language().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_language().data(), static_cast<int>(this->_internal_language().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.SubmitRequest.language");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_language(), target);
  }

  // int32 time_limit = 7;
  if (this->_internal_time_limit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_time_limit(), target);
  }

  // int32 memory_limit = 8;
  if (this->_internal_memory_limit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(8, this->_internal_memory_limit(), target);
  }

  // bool is_custom_test = 9;
  if (this->_internal_is_custom_test() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(9, this->_internal_is_custom_test(), target);
  }

  // string custom_input = 10;
  if (!this->_internal_custom_input().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_custom_input().data(), static_cast<int>(this->_internal_custom_input().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.SubmitRequest.custom_input");
    target = stream->WriteStringMaybeAliased(
        10, this->_internal_custom_input(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oj_judge.SubmitRequest)
  return target;
}

size_t SubmitRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oj_judge.SubmitRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string question_id = 2;
  if (!this->_internal_question_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_question_id());
  }

  // string code = 4;
  if (!this->_internal_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_code());
  }

  // string language = 6;
  if (!this->_internal_language().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_language());
  }

  // string custom_input = 10;
  if (!this->_internal_custom_input().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_custom_input());
  }

  // uint32 submission_id = 1;
  if (this->_internal_submission_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_submission_id());
  }

  // uint32 user_id = 3;
  if (this->_internal_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_user_id());
  }

  // uint64 timestamp = 5;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_timestamp());
  }

  // int32 time_limit = 7;
  if (this->_internal_time_limit() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_time_limit());
  }

  // int32 memory_limit = 8;
  if (this->_internal_memory_limit() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_memory_limit());
  }

  // bool is_custom_test = 9;
  if (this->_internal_is_custom_test() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SubmitRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SubmitRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SubmitRequest::GetClassData() const { return &_class_data_; }


void SubmitRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SubmitRequest*>(&to_msg);
  auto& from = static_cast<const SubmitRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:oj_judge.SubmitRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_question_id().empty()) {
    _this->_internal_set_question_id(from._internal_question_id());
  }
  if (!from._internal_code().empty()) {
    _this->_internal_set_code(from._internal_code());
  }
  if (!from._internal_language().empty()) {
    _this->_internal_set_language(from._internal_language());
  }
  if (!from._internal_custom_input().empty()) {
    _this->_internal_set_custom_input(from._internal_custom_input());
  }
  if (from._internal_submission_id() != 0) {
    _this->_internal_set_submission_id(from._internal_submission_id());
  }
  if (from._internal_user_id() != 0) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  if (from._internal_time_limit() != 0) {
    _this->_internal_set_time_limit(from._internal_time_limit());
  }
  if (from._internal_memory_limit() != 0) {
    _this->_internal_set_memory_limit(from._internal_memory_limit());
  }
  if (from._internal_is_custom_test() != 0) {
    _this->_internal_set_is_custom_test(from._internal_is_custom_test());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SubmitRequest::CopyFrom(const SubmitRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oj_judge.SubmitRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SubmitRequest::IsInitialized() const {
  return true;
}

void SubmitRequest::InternalSwap(SubmitRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.question_id_, lhs_arena,
      &other->_impl_.question_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.code_, lhs_arena,
      &other->_impl_.code_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.language_, lhs_arena,
      &other->_impl_.language_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.custom_input_, lhs_arena,
      &other->_impl_.custom_input_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SubmitRequest, _impl_.is_custom_test_)
      + sizeof(SubmitRequest::_impl_.is_custom_test_)
      - PROTOBUF_FIELD_OFFSET(SubmitRequest, _impl_.submission_id_)>(
          reinterpret_cast<char*>(&_impl_.submission_id_),
          reinterpret_cast<char*>(&other->_impl_.submission_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SubmitRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_judge_5fservice_2eproto_getter, &descriptor_table_judge_5fservice_2eproto_once,
      file_level_metadata_judge_5fservice_2eproto[0]);
}

// ===================================================================

class SubmitStatus::_Internal {
 public:
};

SubmitStatus::SubmitStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:oj_judge.SubmitStatus)
}
SubmitStatus::SubmitStatus(const SubmitStatus& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SubmitStatus* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.time_cost_){}
    , decltype(_impl_.memory_cost_){}
    , decltype(_impl_.result_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.time_cost_, &from._impl_.time_cost_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.result_) -
    reinterpret_cast<char*>(&_impl_.time_cost_)) + sizeof(_impl_.result_));
  // @@protoc_insertion_point(copy_constructor:oj_judge.SubmitStatus)
}

inline void SubmitStatus::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.time_cost_){0}
    , decltype(_impl_.memory_cost_){0}
    , decltype(_impl_.result_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SubmitStatus::~SubmitStatus() {
  // @@protoc_insertion_point(destructor:oj_judge.SubmitStatus)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SubmitStatus::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SubmitStatus::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SubmitStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:oj_judge.SubmitStatus)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.time_cost_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.result_) -
      reinterpret_cast<char*>(&_impl_.time_cost_)) + sizeof(_impl_.result_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SubmitStatus::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 time_cost = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.time_cost_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 memory_cost = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.memory_cost_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .oj_judge.SubmitResult result = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_result(static_cast<::oj_judge::SubmitResult>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SubmitStatus::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:oj_judge.SubmitStatus)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 time_cost = 1;
  if (this->_internal_time_cost() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_time_cost(), target);
  }

  // int32 memory_cost = 2;
  if (this->_internal_memory_cost() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_memory_cost(), target);
  }

  // .oj_judge.SubmitResult result = 3;
  if (this->_internal_result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_result(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oj_judge.SubmitStatus)
  return target;
}

size_t SubmitStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oj_judge.SubmitStatus)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 time_cost = 1;
  if (this->_internal_time_cost() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_time_cost());
  }

  // int32 memory_cost = 2;
  if (this->_internal_memory_cost() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_memory_cost());
  }

  // .oj_judge.SubmitResult result = 3;
  if (this->_internal_result() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_result());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SubmitStatus::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SubmitStatus::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SubmitStatus::GetClassData() const { return &_class_data_; }


void SubmitStatus::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SubmitStatus*>(&to_msg);
  auto& from = static_cast<const SubmitStatus&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:oj_judge.SubmitStatus)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_time_cost() != 0) {
    _this->_internal_set_time_cost(from._internal_time_cost());
  }
  if (from._internal_memory_cost() != 0) {
    _this->_internal_set_memory_cost(from._internal_memory_cost());
  }
  if (from._internal_result() != 0) {
    _this->_internal_set_result(from._internal_result());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SubmitStatus::CopyFrom(const SubmitStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oj_judge.SubmitStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SubmitStatus::IsInitialized() const {
  return true;
}

void SubmitStatus::InternalSwap(SubmitStatus* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SubmitStatus, _impl_.result_)
      + sizeof(SubmitStatus::_impl_.result_)
      - PROTOBUF_FIELD_OFFSET(SubmitStatus, _impl_.time_cost_)>(
          reinterpret_cast<char*>(&_impl_.time_cost_),
          reinterpret_cast<char*>(&other->_impl_.time_cost_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SubmitStatus::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_judge_5fservice_2eproto_getter, &descriptor_table_judge_5fservice_2eproto_once,
      file_level_metadata_judge_5fservice_2eproto[1]);
}

// ===================================================================

class JudgeFinishedRequest::_Internal {
 public:
};

JudgeFinishedRequest::JudgeFinishedRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:oj_judge.JudgeFinishedRequest)
}
JudgeFinishedRequest::JudgeFinishedRequest(const JudgeFinishedRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  JudgeFinishedRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.status_list_){from._impl_.status_list_}
    , decltype(_impl_.question_id_){}
    , decltype(_impl_.submission_id_){}
    , decltype(_impl_.user_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.question_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.question_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_question_id().empty()) {
    _this->_impl_.question_id_.Set(from._internal_question_id(),
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.submission_id_, &from._impl_.submission_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.user_id_) -
    reinterpret_cast<char*>(&_impl_.submission_id_)) + sizeof(_impl_.user_id_));
  // @@protoc_insertion_point(copy_constructor:oj_judge.JudgeFinishedRequest)
}

inline void JudgeFinishedRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.status_list_){arena}
    , decltype(_impl_.question_id_){}
    , decltype(_impl_.submission_id_){0u}
    , decltype(_impl_.user_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.question_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.question_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

JudgeFinishedRequest::~JudgeFinishedRequest() {
  // @@protoc_insertion_point(destructor:oj_judge.JudgeFinishedRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void JudgeFinishedRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.status_list_.~RepeatedPtrField();
  _impl_.question_id_.Destroy();
}

void JudgeFinishedRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void JudgeFinishedRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:oj_judge.JudgeFinishedRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_list_.Clear();
  _impl_.question_id_.ClearToEmpty();
  ::memset(&_impl_.submission_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.user_id_) -
      reinterpret_cast<char*>(&_impl_.submission_id_)) + sizeof(_impl_.user_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* JudgeFinishedRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 submission_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.submission_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string question_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_question_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.JudgeFinishedRequest.question_id"));
        } else
          goto handle_unusual;
        continue;
      // uint32 user_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .oj_judge.SubmitStatus status_list = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_status_list(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* JudgeFinishedRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:oj_judge.JudgeFinishedRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 submission_id = 1;
  if (this->_internal_submission_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_submission_id(), target);
  }

  // string question_id = 2;
  if (!this->_internal_question_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_question_id().data(), static_cast<int>(this->_internal_question_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.JudgeFinishedRequest.question_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_question_id(), target);
  }

  // uint32 user_id = 3;
  if (this->_internal_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_user_id(), target);
  }

  // repeated .oj_judge.SubmitStatus status_list = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_status_list_size()); i < n; i++) {
    const auto& repfield = this->_internal_status_list(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oj_judge.JudgeFinishedRequest)
  return target;
}

size_t JudgeFinishedRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oj_judge.JudgeFinishedRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .oj_judge.SubmitStatus status_list = 4;
  total_size += 1UL * this->_internal_status_list_size();
  for (const auto& msg : this->_impl_.status_list_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string question_id = 2;
  if (!this->_internal_question_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_question_id());
  }

  // uint32 submission_id = 1;
  if (this->_internal_submission_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_submission_id());
  }

  // uint32 user_id = 3;
  if (this->_internal_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_user_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData JudgeFinishedRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    JudgeFinishedRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*JudgeFinishedRequest::GetClassData() const { return &_class_data_; }


void JudgeFinishedRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<JudgeFinishedRequest*>(&to_msg);
  auto& from = static_cast<const JudgeFinishedRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:oj_judge.JudgeFinishedRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.status_list_.MergeFrom(from._impl_.status_list_);
  if (!from._internal_question_id().empty()) {
    _this->_internal_set_question_id(from._internal_question_id());
  }
  if (from._internal_submission_id() != 0) {
    _this->_internal_set_submission_id(from._internal_submission_id());
  }
  if (from._internal_user_id() != 0) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void JudgeFinishedRequest::CopyFrom(const JudgeFinishedRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oj_judge.JudgeFinishedRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JudgeFinishedRequest::IsInitialized() const {
  return true;
}

void JudgeFinishedRequest::InternalSwap(JudgeFinishedRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.status_list_.InternalSwap(&other->_impl_.status_list_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.question_id_, lhs_arena,
      &other->_impl_.question_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(JudgeFinishedRequest, _impl_.user_id_)
      + sizeof(JudgeFinishedRequest::_impl_.user_id_)
      - PROTOBUF_FIELD_OFFSET(JudgeFinishedRequest, _impl_.submission_id_)>(
          reinterpret_cast<char*>(&_impl_.submission_id_),
          reinterpret_cast<char*>(&other->_impl_.submission_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata JudgeFinishedRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_judge_5fservice_2eproto_getter, &descriptor_table_judge_5fservice_2eproto_once,
      file_level_metadata_judge_5fservice_2eproto[2]);
}

// ===================================================================

class DockerWorkDoneRequest::_Internal {
 public:
};

DockerWorkDoneRequest::DockerWorkDoneRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:oj_judge.DockerWorkDoneRequest)
}
DockerWorkDoneRequest::DockerWorkDoneRequest(const DockerWorkDoneRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DockerWorkDoneRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){}
    , decltype(_impl_.status_){}
    , decltype(_impl_.exit_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_id().empty()) {
    _this->_impl_.id_.Set(from._internal_id(),
      _this->GetArenaForAllocation());
  }
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.status_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_status().empty()) {
    _this->_impl_.status_.Set(from._internal_status(),
      _this->GetArenaForAllocation());
  }
  _this->_impl_.exit_code_ = from._impl_.exit_code_;
  // @@protoc_insertion_point(copy_constructor:oj_judge.DockerWorkDoneRequest)
}

inline void DockerWorkDoneRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){}
    , decltype(_impl_.status_){}
    , decltype(_impl_.exit_code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.status_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DockerWorkDoneRequest::~DockerWorkDoneRequest() {
  // @@protoc_insertion_point(destructor:oj_judge.DockerWorkDoneRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DockerWorkDoneRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.id_.Destroy();
  _impl_.status_.Destroy();
}

void DockerWorkDoneRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DockerWorkDoneRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:oj_judge.DockerWorkDoneRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _impl_.status_.ClearToEmpty();
  _impl_.exit_code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DockerWorkDoneRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.DockerWorkDoneRequest.id"));
        } else
          goto handle_unusual;
        continue;
      // string status = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_status();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "oj_judge.DockerWorkDoneRequest.status"));
        } else
          goto handle_unusual;
        continue;
      // int32 exit_code = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.exit_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DockerWorkDoneRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:oj_judge.DockerWorkDoneRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.DockerWorkDoneRequest.id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_id(), target);
  }

  // string status = 2;
  if (!this->_internal_status().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_status().data(), static_cast<int>(this->_internal_status().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "oj_judge.DockerWorkDoneRequest.status");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_status(), target);
  }

  // int32 exit_code = 3;
  if (this->_internal_exit_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_exit_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oj_judge.DockerWorkDoneRequest)
  return target;
}

size_t DockerWorkDoneRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oj_judge.DockerWorkDoneRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  // string status = 2;
  if (!this->_internal_status().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_status());
  }

  // int32 exit_code = 3;
  if (this->_internal_exit_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_exit_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DockerWorkDoneRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DockerWorkDoneRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DockerWorkDoneRequest::GetClassData() const { return &_class_data_; }


void DockerWorkDoneRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DockerWorkDoneRequest*>(&to_msg);
  auto& from = static_cast<const DockerWorkDoneRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:oj_judge.DockerWorkDoneRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (!from._internal_status().empty()) {
    _this->_internal_set_status(from._internal_status());
  }
  if (from._internal_exit_code() != 0) {
    _this->_internal_set_exit_code(from._internal_exit_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DockerWorkDoneRequest::CopyFrom(const DockerWorkDoneRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oj_judge.DockerWorkDoneRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DockerWorkDoneRequest::IsInitialized() const {
  return true;
}

void DockerWorkDoneRequest::InternalSwap(DockerWorkDoneRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.id_, lhs_arena,
      &other->_impl_.id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.status_, lhs_arena,
      &other->_impl_.status_, rhs_arena
  );
  swap(_impl_.exit_code_, other->_impl_.exit_code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DockerWorkDoneRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_judge_5fservice_2eproto_getter, &descriptor_table_judge_5fservice_2eproto_once,
      file_level_metadata_judge_5fservice_2eproto[3]);
}

// ===================================================================

class NullRsp::_Internal {
 public:
};

NullRsp::NullRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:oj_judge.NullRsp)
}
NullRsp::NullRsp(const NullRsp& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  NullRsp* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:oj_judge.NullRsp)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData NullRsp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*NullRsp::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata NullRsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_judge_5fservice_2eproto_getter, &descriptor_table_judge_5fservice_2eproto_once,
      file_level_metadata_judge_5fservice_2eproto[4]);
}

// ===================================================================

JudgeService::~JudgeService() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* JudgeService::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_judge_5fservice_2eproto);
  return file_level_service_descriptors_judge_5fservice_2eproto[0];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* JudgeService::GetDescriptor() {
  return descriptor();
}

void JudgeService::DockerWorkDone(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::oj_judge::DockerWorkDoneRequest*,
                         ::oj_judge::NullRsp*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method DockerWorkDone() not implemented.");
  done->Run();
}

void JudgeService::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_judge_5fservice_2eproto[0]);
  switch(method->index()) {
    case 0:
      DockerWorkDone(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::oj_judge::DockerWorkDoneRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::oj_judge::NullRsp*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& JudgeService::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::oj_judge::DockerWorkDoneRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& JudgeService::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::oj_judge::NullRsp::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

JudgeService_Stub::JudgeService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
JudgeService_Stub::JudgeService_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
JudgeService_Stub::~JudgeService_Stub() {
  if (owns_channel_) delete channel_;
}

void JudgeService_Stub::DockerWorkDone(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::oj_judge::DockerWorkDoneRequest* request,
                              ::oj_judge::NullRsp* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace oj_judge
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::oj_judge::SubmitRequest*
Arena::CreateMaybeMessage< ::oj_judge::SubmitRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::oj_judge::SubmitRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::oj_judge::SubmitStatus*
Arena::CreateMaybeMessage< ::oj_judge::SubmitStatus >(Arena* arena) {
  return Arena::CreateMessageInternal< ::oj_judge::SubmitStatus >(arena);
}
template<> PROTOBUF_NOINLINE ::oj_judge::JudgeFinishedRequest*
Arena::CreateMaybeMessage< ::oj_judge::JudgeFinishedRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::oj_judge::JudgeFinishedRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::oj_judge::DockerWorkDoneRequest*
Arena::CreateMaybeMessage< ::oj_judge::DockerWorkDoneRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::oj_judge::DockerWorkDoneRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::oj_judge::NullRsp*
Arena::CreateMaybeMessage< ::oj_judge::NullRsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::oj_judge::NullRsp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
