// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: judge_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_judge_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_judge_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_judge_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_judge_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_judge_5fservice_2eproto;
namespace oj_judge {
class DockerWorkDoneRequest;
struct DockerWorkDoneRequestDefaultTypeInternal;
extern DockerWorkDoneRequestDefaultTypeInternal _DockerWorkDoneRequest_default_instance_;
class JudgeFinishedRequest;
struct JudgeFinishedRequestDefaultTypeInternal;
extern JudgeFinishedRequestDefaultTypeInternal _JudgeFinishedRequest_default_instance_;
class NullRsp;
struct NullRspDefaultTypeInternal;
extern NullRspDefaultTypeInternal _NullRsp_default_instance_;
class SubmitRequest;
struct SubmitRequestDefaultTypeInternal;
extern SubmitRequestDefaultTypeInternal _SubmitRequest_default_instance_;
class SubmitStatus;
struct SubmitStatusDefaultTypeInternal;
extern SubmitStatusDefaultTypeInternal _SubmitStatus_default_instance_;
}  // namespace oj_judge
PROTOBUF_NAMESPACE_OPEN
template<> ::oj_judge::DockerWorkDoneRequest* Arena::CreateMaybeMessage<::oj_judge::DockerWorkDoneRequest>(Arena*);
template<> ::oj_judge::JudgeFinishedRequest* Arena::CreateMaybeMessage<::oj_judge::JudgeFinishedRequest>(Arena*);
template<> ::oj_judge::NullRsp* Arena::CreateMaybeMessage<::oj_judge::NullRsp>(Arena*);
template<> ::oj_judge::SubmitRequest* Arena::CreateMaybeMessage<::oj_judge::SubmitRequest>(Arena*);
template<> ::oj_judge::SubmitStatus* Arena::CreateMaybeMessage<::oj_judge::SubmitStatus>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace oj_judge {

enum SubmitResult : int {
  AC = 0,
  WA = 1,
  COMPILE_ERROR = 2,
  MEMORY_LIMIT = 3,
  TIME_LIMIT = 4,
  SEGV_ERROR = 5,
  FPE_ERROR = 6,
  RUNTIME_ERROR = 7,
  UNKNOWN = 8,
  SubmitResult_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  SubmitResult_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool SubmitResult_IsValid(int value);
constexpr SubmitResult SubmitResult_MIN = AC;
constexpr SubmitResult SubmitResult_MAX = UNKNOWN;
constexpr int SubmitResult_ARRAYSIZE = SubmitResult_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SubmitResult_descriptor();
template<typename T>
inline const std::string& SubmitResult_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SubmitResult>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SubmitResult_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SubmitResult_descriptor(), enum_t_value);
}
inline bool SubmitResult_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SubmitResult* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SubmitResult>(
    SubmitResult_descriptor(), name, value);
}
// ===================================================================

class SubmitRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj_judge.SubmitRequest) */ {
 public:
  inline SubmitRequest() : SubmitRequest(nullptr) {}
  ~SubmitRequest() override;
  explicit PROTOBUF_CONSTEXPR SubmitRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SubmitRequest(const SubmitRequest& from);
  SubmitRequest(SubmitRequest&& from) noexcept
    : SubmitRequest() {
    *this = ::std::move(from);
  }

  inline SubmitRequest& operator=(const SubmitRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SubmitRequest& operator=(SubmitRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SubmitRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SubmitRequest* internal_default_instance() {
    return reinterpret_cast<const SubmitRequest*>(
               &_SubmitRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SubmitRequest& a, SubmitRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SubmitRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SubmitRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SubmitRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SubmitRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SubmitRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SubmitRequest& from) {
    SubmitRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SubmitRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj_judge.SubmitRequest";
  }
  protected:
  explicit SubmitRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQuestionIdFieldNumber = 2,
    kCodeFieldNumber = 4,
    kLanguageFieldNumber = 6,
    kCustomInputFieldNumber = 10,
    kSubmissionIdFieldNumber = 1,
    kUserIdFieldNumber = 3,
    kTimestampFieldNumber = 5,
    kTimeLimitFieldNumber = 7,
    kMemoryLimitFieldNumber = 8,
    kIsCustomTestFieldNumber = 9,
  };
  // string question_id = 2;
  void clear_question_id();
  const std::string& question_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_question_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_question_id();
  PROTOBUF_NODISCARD std::string* release_question_id();
  void set_allocated_question_id(std::string* question_id);
  private:
  const std::string& _internal_question_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_question_id(const std::string& value);
  std::string* _internal_mutable_question_id();
  public:

  // string code = 4;
  void clear_code();
  const std::string& code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_code();
  PROTOBUF_NODISCARD std::string* release_code();
  void set_allocated_code(std::string* code);
  private:
  const std::string& _internal_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_code(const std::string& value);
  std::string* _internal_mutable_code();
  public:

  // string language = 6;
  void clear_language();
  const std::string& language() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_language(ArgT0&& arg0, ArgT... args);
  std::string* mutable_language();
  PROTOBUF_NODISCARD std::string* release_language();
  void set_allocated_language(std::string* language);
  private:
  const std::string& _internal_language() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_language(const std::string& value);
  std::string* _internal_mutable_language();
  public:

  // string custom_input = 10;
  void clear_custom_input();
  const std::string& custom_input() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_custom_input(ArgT0&& arg0, ArgT... args);
  std::string* mutable_custom_input();
  PROTOBUF_NODISCARD std::string* release_custom_input();
  void set_allocated_custom_input(std::string* custom_input);
  private:
  const std::string& _internal_custom_input() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_custom_input(const std::string& value);
  std::string* _internal_mutable_custom_input();
  public:

  // uint32 submission_id = 1;
  void clear_submission_id();
  uint32_t submission_id() const;
  void set_submission_id(uint32_t value);
  private:
  uint32_t _internal_submission_id() const;
  void _internal_set_submission_id(uint32_t value);
  public:

  // uint32 user_id = 3;
  void clear_user_id();
  uint32_t user_id() const;
  void set_user_id(uint32_t value);
  private:
  uint32_t _internal_user_id() const;
  void _internal_set_user_id(uint32_t value);
  public:

  // uint64 timestamp = 5;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // int32 time_limit = 7;
  void clear_time_limit();
  int32_t time_limit() const;
  void set_time_limit(int32_t value);
  private:
  int32_t _internal_time_limit() const;
  void _internal_set_time_limit(int32_t value);
  public:

  // int32 memory_limit = 8;
  void clear_memory_limit();
  int32_t memory_limit() const;
  void set_memory_limit(int32_t value);
  private:
  int32_t _internal_memory_limit() const;
  void _internal_set_memory_limit(int32_t value);
  public:

  // bool is_custom_test = 9;
  void clear_is_custom_test();
  bool is_custom_test() const;
  void set_is_custom_test(bool value);
  private:
  bool _internal_is_custom_test() const;
  void _internal_set_is_custom_test(bool value);
  public:

  // @@protoc_insertion_point(class_scope:oj_judge.SubmitRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr question_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr code_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr language_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr custom_input_;
    uint32_t submission_id_;
    uint32_t user_id_;
    uint64_t timestamp_;
    int32_t time_limit_;
    int32_t memory_limit_;
    bool is_custom_test_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_judge_5fservice_2eproto;
};
// -------------------------------------------------------------------

class SubmitStatus final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj_judge.SubmitStatus) */ {
 public:
  inline SubmitStatus() : SubmitStatus(nullptr) {}
  ~SubmitStatus() override;
  explicit PROTOBUF_CONSTEXPR SubmitStatus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SubmitStatus(const SubmitStatus& from);
  SubmitStatus(SubmitStatus&& from) noexcept
    : SubmitStatus() {
    *this = ::std::move(from);
  }

  inline SubmitStatus& operator=(const SubmitStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline SubmitStatus& operator=(SubmitStatus&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SubmitStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const SubmitStatus* internal_default_instance() {
    return reinterpret_cast<const SubmitStatus*>(
               &_SubmitStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SubmitStatus& a, SubmitStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(SubmitStatus* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SubmitStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SubmitStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SubmitStatus>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SubmitStatus& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SubmitStatus& from) {
    SubmitStatus::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SubmitStatus* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj_judge.SubmitStatus";
  }
  protected:
  explicit SubmitStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeCostFieldNumber = 1,
    kMemoryCostFieldNumber = 2,
    kResultFieldNumber = 3,
  };
  // int32 time_cost = 1;
  void clear_time_cost();
  int32_t time_cost() const;
  void set_time_cost(int32_t value);
  private:
  int32_t _internal_time_cost() const;
  void _internal_set_time_cost(int32_t value);
  public:

  // int32 memory_cost = 2;
  void clear_memory_cost();
  int32_t memory_cost() const;
  void set_memory_cost(int32_t value);
  private:
  int32_t _internal_memory_cost() const;
  void _internal_set_memory_cost(int32_t value);
  public:

  // .oj_judge.SubmitResult result = 3;
  void clear_result();
  ::oj_judge::SubmitResult result() const;
  void set_result(::oj_judge::SubmitResult value);
  private:
  ::oj_judge::SubmitResult _internal_result() const;
  void _internal_set_result(::oj_judge::SubmitResult value);
  public:

  // @@protoc_insertion_point(class_scope:oj_judge.SubmitStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t time_cost_;
    int32_t memory_cost_;
    int result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_judge_5fservice_2eproto;
};
// -------------------------------------------------------------------

class JudgeFinishedRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj_judge.JudgeFinishedRequest) */ {
 public:
  inline JudgeFinishedRequest() : JudgeFinishedRequest(nullptr) {}
  ~JudgeFinishedRequest() override;
  explicit PROTOBUF_CONSTEXPR JudgeFinishedRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JudgeFinishedRequest(const JudgeFinishedRequest& from);
  JudgeFinishedRequest(JudgeFinishedRequest&& from) noexcept
    : JudgeFinishedRequest() {
    *this = ::std::move(from);
  }

  inline JudgeFinishedRequest& operator=(const JudgeFinishedRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline JudgeFinishedRequest& operator=(JudgeFinishedRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JudgeFinishedRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const JudgeFinishedRequest* internal_default_instance() {
    return reinterpret_cast<const JudgeFinishedRequest*>(
               &_JudgeFinishedRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(JudgeFinishedRequest& a, JudgeFinishedRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(JudgeFinishedRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JudgeFinishedRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JudgeFinishedRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JudgeFinishedRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JudgeFinishedRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JudgeFinishedRequest& from) {
    JudgeFinishedRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JudgeFinishedRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj_judge.JudgeFinishedRequest";
  }
  protected:
  explicit JudgeFinishedRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusListFieldNumber = 4,
    kQuestionIdFieldNumber = 2,
    kSubmissionIdFieldNumber = 1,
    kUserIdFieldNumber = 3,
  };
  // repeated .oj_judge.SubmitStatus status_list = 4;
  int status_list_size() const;
  private:
  int _internal_status_list_size() const;
  public:
  void clear_status_list();
  ::oj_judge::SubmitStatus* mutable_status_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj_judge::SubmitStatus >*
      mutable_status_list();
  private:
  const ::oj_judge::SubmitStatus& _internal_status_list(int index) const;
  ::oj_judge::SubmitStatus* _internal_add_status_list();
  public:
  const ::oj_judge::SubmitStatus& status_list(int index) const;
  ::oj_judge::SubmitStatus* add_status_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj_judge::SubmitStatus >&
      status_list() const;

  // string question_id = 2;
  void clear_question_id();
  const std::string& question_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_question_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_question_id();
  PROTOBUF_NODISCARD std::string* release_question_id();
  void set_allocated_question_id(std::string* question_id);
  private:
  const std::string& _internal_question_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_question_id(const std::string& value);
  std::string* _internal_mutable_question_id();
  public:

  // uint32 submission_id = 1;
  void clear_submission_id();
  uint32_t submission_id() const;
  void set_submission_id(uint32_t value);
  private:
  uint32_t _internal_submission_id() const;
  void _internal_set_submission_id(uint32_t value);
  public:

  // uint32 user_id = 3;
  void clear_user_id();
  uint32_t user_id() const;
  void set_user_id(uint32_t value);
  private:
  uint32_t _internal_user_id() const;
  void _internal_set_user_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:oj_judge.JudgeFinishedRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj_judge::SubmitStatus > status_list_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr question_id_;
    uint32_t submission_id_;
    uint32_t user_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_judge_5fservice_2eproto;
};
// -------------------------------------------------------------------

class DockerWorkDoneRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj_judge.DockerWorkDoneRequest) */ {
 public:
  inline DockerWorkDoneRequest() : DockerWorkDoneRequest(nullptr) {}
  ~DockerWorkDoneRequest() override;
  explicit PROTOBUF_CONSTEXPR DockerWorkDoneRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DockerWorkDoneRequest(const DockerWorkDoneRequest& from);
  DockerWorkDoneRequest(DockerWorkDoneRequest&& from) noexcept
    : DockerWorkDoneRequest() {
    *this = ::std::move(from);
  }

  inline DockerWorkDoneRequest& operator=(const DockerWorkDoneRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DockerWorkDoneRequest& operator=(DockerWorkDoneRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DockerWorkDoneRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DockerWorkDoneRequest* internal_default_instance() {
    return reinterpret_cast<const DockerWorkDoneRequest*>(
               &_DockerWorkDoneRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(DockerWorkDoneRequest& a, DockerWorkDoneRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DockerWorkDoneRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DockerWorkDoneRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DockerWorkDoneRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DockerWorkDoneRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DockerWorkDoneRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DockerWorkDoneRequest& from) {
    DockerWorkDoneRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DockerWorkDoneRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj_judge.DockerWorkDoneRequest";
  }
  protected:
  explicit DockerWorkDoneRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kStatusFieldNumber = 2,
    kExitCodeFieldNumber = 3,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string status = 2;
  void clear_status();
  const std::string& status() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status();
  PROTOBUF_NODISCARD std::string* release_status();
  void set_allocated_status(std::string* status);
  private:
  const std::string& _internal_status() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // int32 exit_code = 3;
  void clear_exit_code();
  int32_t exit_code() const;
  void set_exit_code(int32_t value);
  private:
  int32_t _internal_exit_code() const;
  void _internal_set_exit_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:oj_judge.DockerWorkDoneRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
    int32_t exit_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_judge_5fservice_2eproto;
};
// -------------------------------------------------------------------

class NullRsp final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:oj_judge.NullRsp) */ {
 public:
  inline NullRsp() : NullRsp(nullptr) {}
  explicit PROTOBUF_CONSTEXPR NullRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NullRsp(const NullRsp& from);
  NullRsp(NullRsp&& from) noexcept
    : NullRsp() {
    *this = ::std::move(from);
  }

  inline NullRsp& operator=(const NullRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline NullRsp& operator=(NullRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NullRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const NullRsp* internal_default_instance() {
    return reinterpret_cast<const NullRsp*>(
               &_NullRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(NullRsp& a, NullRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(NullRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NullRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NullRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NullRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const NullRsp& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const NullRsp& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj_judge.NullRsp";
  }
  protected:
  explicit NullRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:oj_judge.NullRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_judge_5fservice_2eproto;
};
// ===================================================================

class JudgeService_Stub;

class JudgeService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline JudgeService() {};
 public:
  virtual ~JudgeService();

  typedef JudgeService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void DockerWorkDone(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oj_judge::DockerWorkDoneRequest* request,
                       ::oj_judge::NullRsp* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(JudgeService);
};

class JudgeService_Stub : public JudgeService {
 public:
  JudgeService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  JudgeService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~JudgeService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements JudgeService ------------------------------------------

  void DockerWorkDone(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::oj_judge::DockerWorkDoneRequest* request,
                       ::oj_judge::NullRsp* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(JudgeService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SubmitRequest

// uint32 submission_id = 1;
inline void SubmitRequest::clear_submission_id() {
  _impl_.submission_id_ = 0u;
}
inline uint32_t SubmitRequest::_internal_submission_id() const {
  return _impl_.submission_id_;
}
inline uint32_t SubmitRequest::submission_id() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.submission_id)
  return _internal_submission_id();
}
inline void SubmitRequest::_internal_set_submission_id(uint32_t value) {

  _impl_.submission_id_ = value;
}
inline void SubmitRequest::set_submission_id(uint32_t value) {
  _internal_set_submission_id(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.submission_id)
}

// string question_id = 2;
inline void SubmitRequest::clear_question_id() {
  _impl_.question_id_.ClearToEmpty();
}
inline const std::string& SubmitRequest::question_id() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.question_id)
  return _internal_question_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubmitRequest::set_question_id(ArgT0&& arg0, ArgT... args) {

 _impl_.question_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.question_id)
}
inline std::string* SubmitRequest::mutable_question_id() {
  std::string* _s = _internal_mutable_question_id();
  // @@protoc_insertion_point(field_mutable:oj_judge.SubmitRequest.question_id)
  return _s;
}
inline const std::string& SubmitRequest::_internal_question_id() const {
  return _impl_.question_id_.Get();
}
inline void SubmitRequest::_internal_set_question_id(const std::string& value) {

  _impl_.question_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SubmitRequest::_internal_mutable_question_id() {

  return _impl_.question_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SubmitRequest::release_question_id() {
  // @@protoc_insertion_point(field_release:oj_judge.SubmitRequest.question_id)
  return _impl_.question_id_.Release();
}
inline void SubmitRequest::set_allocated_question_id(std::string* question_id) {
  if (question_id != nullptr) {

  } else {

  }
  _impl_.question_id_.SetAllocated(question_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.question_id_.IsDefault()) {
    _impl_.question_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.SubmitRequest.question_id)
}

// uint32 user_id = 3;
inline void SubmitRequest::clear_user_id() {
  _impl_.user_id_ = 0u;
}
inline uint32_t SubmitRequest::_internal_user_id() const {
  return _impl_.user_id_;
}
inline uint32_t SubmitRequest::user_id() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.user_id)
  return _internal_user_id();
}
inline void SubmitRequest::_internal_set_user_id(uint32_t value) {

  _impl_.user_id_ = value;
}
inline void SubmitRequest::set_user_id(uint32_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.user_id)
}

// string code = 4;
inline void SubmitRequest::clear_code() {
  _impl_.code_.ClearToEmpty();
}
inline const std::string& SubmitRequest::code() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.code)
  return _internal_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubmitRequest::set_code(ArgT0&& arg0, ArgT... args) {

 _impl_.code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.code)
}
inline std::string* SubmitRequest::mutable_code() {
  std::string* _s = _internal_mutable_code();
  // @@protoc_insertion_point(field_mutable:oj_judge.SubmitRequest.code)
  return _s;
}
inline const std::string& SubmitRequest::_internal_code() const {
  return _impl_.code_.Get();
}
inline void SubmitRequest::_internal_set_code(const std::string& value) {

  _impl_.code_.Set(value, GetArenaForAllocation());
}
inline std::string* SubmitRequest::_internal_mutable_code() {

  return _impl_.code_.Mutable(GetArenaForAllocation());
}
inline std::string* SubmitRequest::release_code() {
  // @@protoc_insertion_point(field_release:oj_judge.SubmitRequest.code)
  return _impl_.code_.Release();
}
inline void SubmitRequest::set_allocated_code(std::string* code) {
  if (code != nullptr) {

  } else {

  }
  _impl_.code_.SetAllocated(code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.code_.IsDefault()) {
    _impl_.code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.SubmitRequest.code)
}

// uint64 timestamp = 5;
inline void SubmitRequest::clear_timestamp() {
  _impl_.timestamp_ = uint64_t{0u};
}
inline uint64_t SubmitRequest::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint64_t SubmitRequest::timestamp() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.timestamp)
  return _internal_timestamp();
}
inline void SubmitRequest::_internal_set_timestamp(uint64_t value) {

  _impl_.timestamp_ = value;
}
inline void SubmitRequest::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.timestamp)
}

// string language = 6;
inline void SubmitRequest::clear_language() {
  _impl_.language_.ClearToEmpty();
}
inline const std::string& SubmitRequest::language() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.language)
  return _internal_language();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubmitRequest::set_language(ArgT0&& arg0, ArgT... args) {

 _impl_.language_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.language)
}
inline std::string* SubmitRequest::mutable_language() {
  std::string* _s = _internal_mutable_language();
  // @@protoc_insertion_point(field_mutable:oj_judge.SubmitRequest.language)
  return _s;
}
inline const std::string& SubmitRequest::_internal_language() const {
  return _impl_.language_.Get();
}
inline void SubmitRequest::_internal_set_language(const std::string& value) {

  _impl_.language_.Set(value, GetArenaForAllocation());
}
inline std::string* SubmitRequest::_internal_mutable_language() {

  return _impl_.language_.Mutable(GetArenaForAllocation());
}
inline std::string* SubmitRequest::release_language() {
  // @@protoc_insertion_point(field_release:oj_judge.SubmitRequest.language)
  return _impl_.language_.Release();
}
inline void SubmitRequest::set_allocated_language(std::string* language) {
  if (language != nullptr) {

  } else {

  }
  _impl_.language_.SetAllocated(language, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.language_.IsDefault()) {
    _impl_.language_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.SubmitRequest.language)
}

// int32 time_limit = 7;
inline void SubmitRequest::clear_time_limit() {
  _impl_.time_limit_ = 0;
}
inline int32_t SubmitRequest::_internal_time_limit() const {
  return _impl_.time_limit_;
}
inline int32_t SubmitRequest::time_limit() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.time_limit)
  return _internal_time_limit();
}
inline void SubmitRequest::_internal_set_time_limit(int32_t value) {

  _impl_.time_limit_ = value;
}
inline void SubmitRequest::set_time_limit(int32_t value) {
  _internal_set_time_limit(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.time_limit)
}

// int32 memory_limit = 8;
inline void SubmitRequest::clear_memory_limit() {
  _impl_.memory_limit_ = 0;
}
inline int32_t SubmitRequest::_internal_memory_limit() const {
  return _impl_.memory_limit_;
}
inline int32_t SubmitRequest::memory_limit() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.memory_limit)
  return _internal_memory_limit();
}
inline void SubmitRequest::_internal_set_memory_limit(int32_t value) {

  _impl_.memory_limit_ = value;
}
inline void SubmitRequest::set_memory_limit(int32_t value) {
  _internal_set_memory_limit(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.memory_limit)
}

// bool is_custom_test = 9;
inline void SubmitRequest::clear_is_custom_test() {
  _impl_.is_custom_test_ = false;
}
inline bool SubmitRequest::_internal_is_custom_test() const {
  return _impl_.is_custom_test_;
}
inline bool SubmitRequest::is_custom_test() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.is_custom_test)
  return _internal_is_custom_test();
}
inline void SubmitRequest::_internal_set_is_custom_test(bool value) {

  _impl_.is_custom_test_ = value;
}
inline void SubmitRequest::set_is_custom_test(bool value) {
  _internal_set_is_custom_test(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.is_custom_test)
}

// string custom_input = 10;
inline void SubmitRequest::clear_custom_input() {
  _impl_.custom_input_.ClearToEmpty();
}
inline const std::string& SubmitRequest::custom_input() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitRequest.custom_input)
  return _internal_custom_input();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubmitRequest::set_custom_input(ArgT0&& arg0, ArgT... args) {

 _impl_.custom_input_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.SubmitRequest.custom_input)
}
inline std::string* SubmitRequest::mutable_custom_input() {
  std::string* _s = _internal_mutable_custom_input();
  // @@protoc_insertion_point(field_mutable:oj_judge.SubmitRequest.custom_input)
  return _s;
}
inline const std::string& SubmitRequest::_internal_custom_input() const {
  return _impl_.custom_input_.Get();
}
inline void SubmitRequest::_internal_set_custom_input(const std::string& value) {

  _impl_.custom_input_.Set(value, GetArenaForAllocation());
}
inline std::string* SubmitRequest::_internal_mutable_custom_input() {

  return _impl_.custom_input_.Mutable(GetArenaForAllocation());
}
inline std::string* SubmitRequest::release_custom_input() {
  // @@protoc_insertion_point(field_release:oj_judge.SubmitRequest.custom_input)
  return _impl_.custom_input_.Release();
}
inline void SubmitRequest::set_allocated_custom_input(std::string* custom_input) {
  if (custom_input != nullptr) {

  } else {

  }
  _impl_.custom_input_.SetAllocated(custom_input, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.custom_input_.IsDefault()) {
    _impl_.custom_input_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.SubmitRequest.custom_input)
}

// -------------------------------------------------------------------

// SubmitStatus

// int32 time_cost = 1;
inline void SubmitStatus::clear_time_cost() {
  _impl_.time_cost_ = 0;
}
inline int32_t SubmitStatus::_internal_time_cost() const {
  return _impl_.time_cost_;
}
inline int32_t SubmitStatus::time_cost() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitStatus.time_cost)
  return _internal_time_cost();
}
inline void SubmitStatus::_internal_set_time_cost(int32_t value) {

  _impl_.time_cost_ = value;
}
inline void SubmitStatus::set_time_cost(int32_t value) {
  _internal_set_time_cost(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitStatus.time_cost)
}

// int32 memory_cost = 2;
inline void SubmitStatus::clear_memory_cost() {
  _impl_.memory_cost_ = 0;
}
inline int32_t SubmitStatus::_internal_memory_cost() const {
  return _impl_.memory_cost_;
}
inline int32_t SubmitStatus::memory_cost() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitStatus.memory_cost)
  return _internal_memory_cost();
}
inline void SubmitStatus::_internal_set_memory_cost(int32_t value) {

  _impl_.memory_cost_ = value;
}
inline void SubmitStatus::set_memory_cost(int32_t value) {
  _internal_set_memory_cost(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitStatus.memory_cost)
}

// .oj_judge.SubmitResult result = 3;
inline void SubmitStatus::clear_result() {
  _impl_.result_ = 0;
}
inline ::oj_judge::SubmitResult SubmitStatus::_internal_result() const {
  return static_cast< ::oj_judge::SubmitResult >(_impl_.result_);
}
inline ::oj_judge::SubmitResult SubmitStatus::result() const {
  // @@protoc_insertion_point(field_get:oj_judge.SubmitStatus.result)
  return _internal_result();
}
inline void SubmitStatus::_internal_set_result(::oj_judge::SubmitResult value) {

  _impl_.result_ = value;
}
inline void SubmitStatus::set_result(::oj_judge::SubmitResult value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:oj_judge.SubmitStatus.result)
}

// -------------------------------------------------------------------

// JudgeFinishedRequest

// uint32 submission_id = 1;
inline void JudgeFinishedRequest::clear_submission_id() {
  _impl_.submission_id_ = 0u;
}
inline uint32_t JudgeFinishedRequest::_internal_submission_id() const {
  return _impl_.submission_id_;
}
inline uint32_t JudgeFinishedRequest::submission_id() const {
  // @@protoc_insertion_point(field_get:oj_judge.JudgeFinishedRequest.submission_id)
  return _internal_submission_id();
}
inline void JudgeFinishedRequest::_internal_set_submission_id(uint32_t value) {

  _impl_.submission_id_ = value;
}
inline void JudgeFinishedRequest::set_submission_id(uint32_t value) {
  _internal_set_submission_id(value);
  // @@protoc_insertion_point(field_set:oj_judge.JudgeFinishedRequest.submission_id)
}

// string question_id = 2;
inline void JudgeFinishedRequest::clear_question_id() {
  _impl_.question_id_.ClearToEmpty();
}
inline const std::string& JudgeFinishedRequest::question_id() const {
  // @@protoc_insertion_point(field_get:oj_judge.JudgeFinishedRequest.question_id)
  return _internal_question_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeFinishedRequest::set_question_id(ArgT0&& arg0, ArgT... args) {

 _impl_.question_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.JudgeFinishedRequest.question_id)
}
inline std::string* JudgeFinishedRequest::mutable_question_id() {
  std::string* _s = _internal_mutable_question_id();
  // @@protoc_insertion_point(field_mutable:oj_judge.JudgeFinishedRequest.question_id)
  return _s;
}
inline const std::string& JudgeFinishedRequest::_internal_question_id() const {
  return _impl_.question_id_.Get();
}
inline void JudgeFinishedRequest::_internal_set_question_id(const std::string& value) {

  _impl_.question_id_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeFinishedRequest::_internal_mutable_question_id() {

  return _impl_.question_id_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeFinishedRequest::release_question_id() {
  // @@protoc_insertion_point(field_release:oj_judge.JudgeFinishedRequest.question_id)
  return _impl_.question_id_.Release();
}
inline void JudgeFinishedRequest::set_allocated_question_id(std::string* question_id) {
  if (question_id != nullptr) {

  } else {

  }
  _impl_.question_id_.SetAllocated(question_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.question_id_.IsDefault()) {
    _impl_.question_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.JudgeFinishedRequest.question_id)
}

// uint32 user_id = 3;
inline void JudgeFinishedRequest::clear_user_id() {
  _impl_.user_id_ = 0u;
}
inline uint32_t JudgeFinishedRequest::_internal_user_id() const {
  return _impl_.user_id_;
}
inline uint32_t JudgeFinishedRequest::user_id() const {
  // @@protoc_insertion_point(field_get:oj_judge.JudgeFinishedRequest.user_id)
  return _internal_user_id();
}
inline void JudgeFinishedRequest::_internal_set_user_id(uint32_t value) {

  _impl_.user_id_ = value;
}
inline void JudgeFinishedRequest::set_user_id(uint32_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:oj_judge.JudgeFinishedRequest.user_id)
}

// repeated .oj_judge.SubmitStatus status_list = 4;
inline int JudgeFinishedRequest::_internal_status_list_size() const {
  return _impl_.status_list_.size();
}
inline int JudgeFinishedRequest::status_list_size() const {
  return _internal_status_list_size();
}
inline void JudgeFinishedRequest::clear_status_list() {
  _impl_.status_list_.Clear();
}
inline ::oj_judge::SubmitStatus* JudgeFinishedRequest::mutable_status_list(int index) {
  // @@protoc_insertion_point(field_mutable:oj_judge.JudgeFinishedRequest.status_list)
  return _impl_.status_list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj_judge::SubmitStatus >*
JudgeFinishedRequest::mutable_status_list() {
  // @@protoc_insertion_point(field_mutable_list:oj_judge.JudgeFinishedRequest.status_list)
  return &_impl_.status_list_;
}
inline const ::oj_judge::SubmitStatus& JudgeFinishedRequest::_internal_status_list(int index) const {
  return _impl_.status_list_.Get(index);
}
inline const ::oj_judge::SubmitStatus& JudgeFinishedRequest::status_list(int index) const {
  // @@protoc_insertion_point(field_get:oj_judge.JudgeFinishedRequest.status_list)
  return _internal_status_list(index);
}
inline ::oj_judge::SubmitStatus* JudgeFinishedRequest::_internal_add_status_list() {
  return _impl_.status_list_.Add();
}
inline ::oj_judge::SubmitStatus* JudgeFinishedRequest::add_status_list() {
  ::oj_judge::SubmitStatus* _add = _internal_add_status_list();
  // @@protoc_insertion_point(field_add:oj_judge.JudgeFinishedRequest.status_list)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj_judge::SubmitStatus >&
JudgeFinishedRequest::status_list() const {
  // @@protoc_insertion_point(field_list:oj_judge.JudgeFinishedRequest.status_list)
  return _impl_.status_list_;
}

// -------------------------------------------------------------------

// DockerWorkDoneRequest

// string id = 1;
inline void DockerWorkDoneRequest::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& DockerWorkDoneRequest::id() const {
  // @@protoc_insertion_point(field_get:oj_judge.DockerWorkDoneRequest.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DockerWorkDoneRequest::set_id(ArgT0&& arg0, ArgT... args) {

 _impl_.id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.DockerWorkDoneRequest.id)
}
inline std::string* DockerWorkDoneRequest::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:oj_judge.DockerWorkDoneRequest.id)
  return _s;
}
inline const std::string& DockerWorkDoneRequest::_internal_id() const {
  return _impl_.id_.Get();
}
inline void DockerWorkDoneRequest::_internal_set_id(const std::string& value) {

  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* DockerWorkDoneRequest::_internal_mutable_id() {

  return _impl_.id_.Mutable(GetArenaForAllocation());
}
inline std::string* DockerWorkDoneRequest::release_id() {
  // @@protoc_insertion_point(field_release:oj_judge.DockerWorkDoneRequest.id)
  return _impl_.id_.Release();
}
inline void DockerWorkDoneRequest::set_allocated_id(std::string* id) {
  if (id != nullptr) {

  } else {

  }
  _impl_.id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.DockerWorkDoneRequest.id)
}

// string status = 2;
inline void DockerWorkDoneRequest::clear_status() {
  _impl_.status_.ClearToEmpty();
}
inline const std::string& DockerWorkDoneRequest::status() const {
  // @@protoc_insertion_point(field_get:oj_judge.DockerWorkDoneRequest.status)
  return _internal_status();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DockerWorkDoneRequest::set_status(ArgT0&& arg0, ArgT... args) {

 _impl_.status_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj_judge.DockerWorkDoneRequest.status)
}
inline std::string* DockerWorkDoneRequest::mutable_status() {
  std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:oj_judge.DockerWorkDoneRequest.status)
  return _s;
}
inline const std::string& DockerWorkDoneRequest::_internal_status() const {
  return _impl_.status_.Get();
}
inline void DockerWorkDoneRequest::_internal_set_status(const std::string& value) {

  _impl_.status_.Set(value, GetArenaForAllocation());
}
inline std::string* DockerWorkDoneRequest::_internal_mutable_status() {

  return _impl_.status_.Mutable(GetArenaForAllocation());
}
inline std::string* DockerWorkDoneRequest::release_status() {
  // @@protoc_insertion_point(field_release:oj_judge.DockerWorkDoneRequest.status)
  return _impl_.status_.Release();
}
inline void DockerWorkDoneRequest::set_allocated_status(std::string* status) {
  if (status != nullptr) {

  } else {

  }
  _impl_.status_.SetAllocated(status, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj_judge.DockerWorkDoneRequest.status)
}

// int32 exit_code = 3;
inline void DockerWorkDoneRequest::clear_exit_code() {
  _impl_.exit_code_ = 0;
}
inline int32_t DockerWorkDoneRequest::_internal_exit_code() const {
  return _impl_.exit_code_;
}
inline int32_t DockerWorkDoneRequest::exit_code() const {
  // @@protoc_insertion_point(field_get:oj_judge.DockerWorkDoneRequest.exit_code)
  return _internal_exit_code();
}
inline void DockerWorkDoneRequest::_internal_set_exit_code(int32_t value) {

  _impl_.exit_code_ = value;
}
inline void DockerWorkDoneRequest::set_exit_code(int32_t value) {
  _internal_set_exit_code(value);
  // @@protoc_insertion_point(field_set:oj_judge.DockerWorkDoneRequest.exit_code)
}

// -------------------------------------------------------------------

// NullRsp

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace oj_judge

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::oj_judge::SubmitResult> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::oj_judge::SubmitResult>() {
  return ::oj_judge::SubmitResult_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_judge_5fservice_2eproto
