// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mq_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mq_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mq_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mq_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mq_5fmessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mq_5fmessage_2eproto;
namespace oj {
namespace mq {
class JudgeResultCallback;
struct JudgeResultCallbackDefaultTypeInternal;
extern JudgeResultCallbackDefaultTypeInternal _JudgeResultCallback_default_instance_;
class JudgeTaskMessage;
struct JudgeTaskMessageDefaultTypeInternal;
extern JudgeTaskMessageDefaultTypeInternal _JudgeTaskMessage_default_instance_;
class TestCaseInput;
struct TestCaseInputDefaultTypeInternal;
extern TestCaseInputDefaultTypeInternal _TestCaseInput_default_instance_;
}  // namespace mq
}  // namespace oj
PROTOBUF_NAMESPACE_OPEN
template<> ::oj::mq::JudgeResultCallback* Arena::CreateMaybeMessage<::oj::mq::JudgeResultCallback>(Arena*);
template<> ::oj::mq::JudgeTaskMessage* Arena::CreateMaybeMessage<::oj::mq::JudgeTaskMessage>(Arena*);
template<> ::oj::mq::TestCaseInput* Arena::CreateMaybeMessage<::oj::mq::TestCaseInput>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace oj {
namespace mq {

// ===================================================================

class TestCaseInput final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj.mq.TestCaseInput) */ {
 public:
  inline TestCaseInput() : TestCaseInput(nullptr) {}
  ~TestCaseInput() override;
  explicit PROTOBUF_CONSTEXPR TestCaseInput(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TestCaseInput(const TestCaseInput& from);
  TestCaseInput(TestCaseInput&& from) noexcept
    : TestCaseInput() {
    *this = ::std::move(from);
  }

  inline TestCaseInput& operator=(const TestCaseInput& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestCaseInput& operator=(TestCaseInput&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestCaseInput& default_instance() {
    return *internal_default_instance();
  }
  static inline const TestCaseInput* internal_default_instance() {
    return reinterpret_cast<const TestCaseInput*>(
               &_TestCaseInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TestCaseInput& a, TestCaseInput& b) {
    a.Swap(&b);
  }
  inline void Swap(TestCaseInput* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestCaseInput* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestCaseInput* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TestCaseInput>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TestCaseInput& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TestCaseInput& from) {
    TestCaseInput::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestCaseInput* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj.mq.TestCaseInput";
  }
  protected:
  explicit TestCaseInput(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInputFieldNumber = 1,
    kExpectedOutputFieldNumber = 2,
  };
  // string input = 1;
  void clear_input();
  const std::string& input() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_input(ArgT0&& arg0, ArgT... args);
  std::string* mutable_input();
  PROTOBUF_NODISCARD std::string* release_input();
  void set_allocated_input(std::string* input);
  private:
  const std::string& _internal_input() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_input(const std::string& value);
  std::string* _internal_mutable_input();
  public:

  // string expected_output = 2;
  void clear_expected_output();
  const std::string& expected_output() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_expected_output(ArgT0&& arg0, ArgT... args);
  std::string* mutable_expected_output();
  PROTOBUF_NODISCARD std::string* release_expected_output();
  void set_allocated_expected_output(std::string* expected_output);
  private:
  const std::string& _internal_expected_output() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_expected_output(const std::string& value);
  std::string* _internal_mutable_expected_output();
  public:

  // @@protoc_insertion_point(class_scope:oj.mq.TestCaseInput)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr input_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr expected_output_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mq_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class JudgeTaskMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj.mq.JudgeTaskMessage) */ {
 public:
  inline JudgeTaskMessage() : JudgeTaskMessage(nullptr) {}
  ~JudgeTaskMessage() override;
  explicit PROTOBUF_CONSTEXPR JudgeTaskMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JudgeTaskMessage(const JudgeTaskMessage& from);
  JudgeTaskMessage(JudgeTaskMessage&& from) noexcept
    : JudgeTaskMessage() {
    *this = ::std::move(from);
  }

  inline JudgeTaskMessage& operator=(const JudgeTaskMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline JudgeTaskMessage& operator=(JudgeTaskMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JudgeTaskMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const JudgeTaskMessage* internal_default_instance() {
    return reinterpret_cast<const JudgeTaskMessage*>(
               &_JudgeTaskMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(JudgeTaskMessage& a, JudgeTaskMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(JudgeTaskMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JudgeTaskMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JudgeTaskMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JudgeTaskMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JudgeTaskMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JudgeTaskMessage& from) {
    JudgeTaskMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JudgeTaskMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj.mq.JudgeTaskMessage";
  }
  protected:
  explicit JudgeTaskMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTestCasesFieldNumber = 12,
    kQuestionIdFieldNumber = 2,
    kCodeFieldNumber = 4,
    kLanguageFieldNumber = 5,
    kCustomInputFieldNumber = 7,
    kSubmissionIdFieldNumber = 1,
    kUserIdFieldNumber = 3,
    kIsCustomTestFieldNumber = 6,
    kTimeLimitFieldNumber = 8,
    kTimestampFieldNumber = 10,
    kMemoryLimitFieldNumber = 9,
    kRetryCountFieldNumber = 11,
  };
  // repeated .oj.mq.TestCaseInput test_cases = 12;
  int test_cases_size() const;
  private:
  int _internal_test_cases_size() const;
  public:
  void clear_test_cases();
  ::oj::mq::TestCaseInput* mutable_test_cases(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj::mq::TestCaseInput >*
      mutable_test_cases();
  private:
  const ::oj::mq::TestCaseInput& _internal_test_cases(int index) const;
  ::oj::mq::TestCaseInput* _internal_add_test_cases();
  public:
  const ::oj::mq::TestCaseInput& test_cases(int index) const;
  ::oj::mq::TestCaseInput* add_test_cases();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj::mq::TestCaseInput >&
      test_cases() const;

  // string question_id = 2;
  void clear_question_id();
  const std::string& question_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_question_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_question_id();
  PROTOBUF_NODISCARD std::string* release_question_id();
  void set_allocated_question_id(std::string* question_id);
  private:
  const std::string& _internal_question_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_question_id(const std::string& value);
  std::string* _internal_mutable_question_id();
  public:

  // string code = 4;
  void clear_code();
  const std::string& code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_code();
  PROTOBUF_NODISCARD std::string* release_code();
  void set_allocated_code(std::string* code);
  private:
  const std::string& _internal_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_code(const std::string& value);
  std::string* _internal_mutable_code();
  public:

  // string language = 5;
  void clear_language();
  const std::string& language() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_language(ArgT0&& arg0, ArgT... args);
  std::string* mutable_language();
  PROTOBUF_NODISCARD std::string* release_language();
  void set_allocated_language(std::string* language);
  private:
  const std::string& _internal_language() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_language(const std::string& value);
  std::string* _internal_mutable_language();
  public:

  // string custom_input = 7;
  void clear_custom_input();
  const std::string& custom_input() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_custom_input(ArgT0&& arg0, ArgT... args);
  std::string* mutable_custom_input();
  PROTOBUF_NODISCARD std::string* release_custom_input();
  void set_allocated_custom_input(std::string* custom_input);
  private:
  const std::string& _internal_custom_input() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_custom_input(const std::string& value);
  std::string* _internal_mutable_custom_input();
  public:

  // uint32 submission_id = 1;
  void clear_submission_id();
  uint32_t submission_id() const;
  void set_submission_id(uint32_t value);
  private:
  uint32_t _internal_submission_id() const;
  void _internal_set_submission_id(uint32_t value);
  public:

  // uint32 user_id = 3;
  void clear_user_id();
  uint32_t user_id() const;
  void set_user_id(uint32_t value);
  private:
  uint32_t _internal_user_id() const;
  void _internal_set_user_id(uint32_t value);
  public:

  // bool is_custom_test = 6;
  void clear_is_custom_test();
  bool is_custom_test() const;
  void set_is_custom_test(bool value);
  private:
  bool _internal_is_custom_test() const;
  void _internal_set_is_custom_test(bool value);
  public:

  // int32 time_limit = 8;
  void clear_time_limit();
  int32_t time_limit() const;
  void set_time_limit(int32_t value);
  private:
  int32_t _internal_time_limit() const;
  void _internal_set_time_limit(int32_t value);
  public:

  // int64 timestamp = 10;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // int32 memory_limit = 9;
  void clear_memory_limit();
  int32_t memory_limit() const;
  void set_memory_limit(int32_t value);
  private:
  int32_t _internal_memory_limit() const;
  void _internal_set_memory_limit(int32_t value);
  public:

  // uint32 retry_count = 11;
  void clear_retry_count();
  uint32_t retry_count() const;
  void set_retry_count(uint32_t value);
  private:
  uint32_t _internal_retry_count() const;
  void _internal_set_retry_count(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:oj.mq.JudgeTaskMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj::mq::TestCaseInput > test_cases_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr question_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr code_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr language_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr custom_input_;
    uint32_t submission_id_;
    uint32_t user_id_;
    bool is_custom_test_;
    int32_t time_limit_;
    int64_t timestamp_;
    int32_t memory_limit_;
    uint32_t retry_count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mq_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class JudgeResultCallback final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj.mq.JudgeResultCallback) */ {
 public:
  inline JudgeResultCallback() : JudgeResultCallback(nullptr) {}
  ~JudgeResultCallback() override;
  explicit PROTOBUF_CONSTEXPR JudgeResultCallback(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JudgeResultCallback(const JudgeResultCallback& from);
  JudgeResultCallback(JudgeResultCallback&& from) noexcept
    : JudgeResultCallback() {
    *this = ::std::move(from);
  }

  inline JudgeResultCallback& operator=(const JudgeResultCallback& from) {
    CopyFrom(from);
    return *this;
  }
  inline JudgeResultCallback& operator=(JudgeResultCallback&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JudgeResultCallback& default_instance() {
    return *internal_default_instance();
  }
  static inline const JudgeResultCallback* internal_default_instance() {
    return reinterpret_cast<const JudgeResultCallback*>(
               &_JudgeResultCallback_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(JudgeResultCallback& a, JudgeResultCallback& b) {
    a.Swap(&b);
  }
  inline void Swap(JudgeResultCallback* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JudgeResultCallback* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JudgeResultCallback* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JudgeResultCallback>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JudgeResultCallback& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JudgeResultCallback& from) {
    JudgeResultCallback::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JudgeResultCallback* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj.mq.JudgeResultCallback";
  }
  protected:
  explicit JudgeResultCallback(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 2,
    kCompileErrorFieldNumber = 5,
    kTestCasesJsonFieldNumber = 6,
    kSubmissionIdFieldNumber = 1,
    kTimeUsedMsFieldNumber = 3,
    kMemoryUsedBytesFieldNumber = 4,
    kCompletedAtFieldNumber = 7,
  };
  // string status = 2;
  void clear_status();
  const std::string& status() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status();
  PROTOBUF_NODISCARD std::string* release_status();
  void set_allocated_status(std::string* status);
  private:
  const std::string& _internal_status() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // string compile_error = 5;
  void clear_compile_error();
  const std::string& compile_error() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_compile_error(ArgT0&& arg0, ArgT... args);
  std::string* mutable_compile_error();
  PROTOBUF_NODISCARD std::string* release_compile_error();
  void set_allocated_compile_error(std::string* compile_error);
  private:
  const std::string& _internal_compile_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_compile_error(const std::string& value);
  std::string* _internal_mutable_compile_error();
  public:

  // string test_cases_json = 6;
  void clear_test_cases_json();
  const std::string& test_cases_json() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_test_cases_json(ArgT0&& arg0, ArgT... args);
  std::string* mutable_test_cases_json();
  PROTOBUF_NODISCARD std::string* release_test_cases_json();
  void set_allocated_test_cases_json(std::string* test_cases_json);
  private:
  const std::string& _internal_test_cases_json() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_test_cases_json(const std::string& value);
  std::string* _internal_mutable_test_cases_json();
  public:

  // uint32 submission_id = 1;
  void clear_submission_id();
  uint32_t submission_id() const;
  void set_submission_id(uint32_t value);
  private:
  uint32_t _internal_submission_id() const;
  void _internal_set_submission_id(uint32_t value);
  public:

  // int32 time_used_ms = 3;
  void clear_time_used_ms();
  int32_t time_used_ms() const;
  void set_time_used_ms(int32_t value);
  private:
  int32_t _internal_time_used_ms() const;
  void _internal_set_time_used_ms(int32_t value);
  public:

  // int64 memory_used_bytes = 4;
  void clear_memory_used_bytes();
  int64_t memory_used_bytes() const;
  void set_memory_used_bytes(int64_t value);
  private:
  int64_t _internal_memory_used_bytes() const;
  void _internal_set_memory_used_bytes(int64_t value);
  public:

  // int64 completed_at = 7;
  void clear_completed_at();
  int64_t completed_at() const;
  void set_completed_at(int64_t value);
  private:
  int64_t _internal_completed_at() const;
  void _internal_set_completed_at(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:oj.mq.JudgeResultCallback)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr compile_error_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr test_cases_json_;
    uint32_t submission_id_;
    int32_t time_used_ms_;
    int64_t memory_used_bytes_;
    int64_t completed_at_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mq_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TestCaseInput

// string input = 1;
inline void TestCaseInput::clear_input() {
  _impl_.input_.ClearToEmpty();
}
inline const std::string& TestCaseInput::input() const {
  // @@protoc_insertion_point(field_get:oj.mq.TestCaseInput.input)
  return _internal_input();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TestCaseInput::set_input(ArgT0&& arg0, ArgT... args) {
 
 _impl_.input_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.TestCaseInput.input)
}
inline std::string* TestCaseInput::mutable_input() {
  std::string* _s = _internal_mutable_input();
  // @@protoc_insertion_point(field_mutable:oj.mq.TestCaseInput.input)
  return _s;
}
inline const std::string& TestCaseInput::_internal_input() const {
  return _impl_.input_.Get();
}
inline void TestCaseInput::_internal_set_input(const std::string& value) {
  
  _impl_.input_.Set(value, GetArenaForAllocation());
}
inline std::string* TestCaseInput::_internal_mutable_input() {
  
  return _impl_.input_.Mutable(GetArenaForAllocation());
}
inline std::string* TestCaseInput::release_input() {
  // @@protoc_insertion_point(field_release:oj.mq.TestCaseInput.input)
  return _impl_.input_.Release();
}
inline void TestCaseInput::set_allocated_input(std::string* input) {
  if (input != nullptr) {
    
  } else {
    
  }
  _impl_.input_.SetAllocated(input, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.input_.IsDefault()) {
    _impl_.input_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.TestCaseInput.input)
}

// string expected_output = 2;
inline void TestCaseInput::clear_expected_output() {
  _impl_.expected_output_.ClearToEmpty();
}
inline const std::string& TestCaseInput::expected_output() const {
  // @@protoc_insertion_point(field_get:oj.mq.TestCaseInput.expected_output)
  return _internal_expected_output();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TestCaseInput::set_expected_output(ArgT0&& arg0, ArgT... args) {
 
 _impl_.expected_output_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.TestCaseInput.expected_output)
}
inline std::string* TestCaseInput::mutable_expected_output() {
  std::string* _s = _internal_mutable_expected_output();
  // @@protoc_insertion_point(field_mutable:oj.mq.TestCaseInput.expected_output)
  return _s;
}
inline const std::string& TestCaseInput::_internal_expected_output() const {
  return _impl_.expected_output_.Get();
}
inline void TestCaseInput::_internal_set_expected_output(const std::string& value) {
  
  _impl_.expected_output_.Set(value, GetArenaForAllocation());
}
inline std::string* TestCaseInput::_internal_mutable_expected_output() {
  
  return _impl_.expected_output_.Mutable(GetArenaForAllocation());
}
inline std::string* TestCaseInput::release_expected_output() {
  // @@protoc_insertion_point(field_release:oj.mq.TestCaseInput.expected_output)
  return _impl_.expected_output_.Release();
}
inline void TestCaseInput::set_allocated_expected_output(std::string* expected_output) {
  if (expected_output != nullptr) {
    
  } else {
    
  }
  _impl_.expected_output_.SetAllocated(expected_output, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.expected_output_.IsDefault()) {
    _impl_.expected_output_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.TestCaseInput.expected_output)
}

// -------------------------------------------------------------------

// JudgeTaskMessage

// uint32 submission_id = 1;
inline void JudgeTaskMessage::clear_submission_id() {
  _impl_.submission_id_ = 0u;
}
inline uint32_t JudgeTaskMessage::_internal_submission_id() const {
  return _impl_.submission_id_;
}
inline uint32_t JudgeTaskMessage::submission_id() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.submission_id)
  return _internal_submission_id();
}
inline void JudgeTaskMessage::_internal_set_submission_id(uint32_t value) {
  
  _impl_.submission_id_ = value;
}
inline void JudgeTaskMessage::set_submission_id(uint32_t value) {
  _internal_set_submission_id(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.submission_id)
}

// string question_id = 2;
inline void JudgeTaskMessage::clear_question_id() {
  _impl_.question_id_.ClearToEmpty();
}
inline const std::string& JudgeTaskMessage::question_id() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.question_id)
  return _internal_question_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeTaskMessage::set_question_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.question_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.question_id)
}
inline std::string* JudgeTaskMessage::mutable_question_id() {
  std::string* _s = _internal_mutable_question_id();
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeTaskMessage.question_id)
  return _s;
}
inline const std::string& JudgeTaskMessage::_internal_question_id() const {
  return _impl_.question_id_.Get();
}
inline void JudgeTaskMessage::_internal_set_question_id(const std::string& value) {
  
  _impl_.question_id_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::_internal_mutable_question_id() {
  
  return _impl_.question_id_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::release_question_id() {
  // @@protoc_insertion_point(field_release:oj.mq.JudgeTaskMessage.question_id)
  return _impl_.question_id_.Release();
}
inline void JudgeTaskMessage::set_allocated_question_id(std::string* question_id) {
  if (question_id != nullptr) {
    
  } else {
    
  }
  _impl_.question_id_.SetAllocated(question_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.question_id_.IsDefault()) {
    _impl_.question_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.JudgeTaskMessage.question_id)
}

// uint32 user_id = 3;
inline void JudgeTaskMessage::clear_user_id() {
  _impl_.user_id_ = 0u;
}
inline uint32_t JudgeTaskMessage::_internal_user_id() const {
  return _impl_.user_id_;
}
inline uint32_t JudgeTaskMessage::user_id() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.user_id)
  return _internal_user_id();
}
inline void JudgeTaskMessage::_internal_set_user_id(uint32_t value) {
  
  _impl_.user_id_ = value;
}
inline void JudgeTaskMessage::set_user_id(uint32_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.user_id)
}

// string code = 4;
inline void JudgeTaskMessage::clear_code() {
  _impl_.code_.ClearToEmpty();
}
inline const std::string& JudgeTaskMessage::code() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.code)
  return _internal_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeTaskMessage::set_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.code)
}
inline std::string* JudgeTaskMessage::mutable_code() {
  std::string* _s = _internal_mutable_code();
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeTaskMessage.code)
  return _s;
}
inline const std::string& JudgeTaskMessage::_internal_code() const {
  return _impl_.code_.Get();
}
inline void JudgeTaskMessage::_internal_set_code(const std::string& value) {
  
  _impl_.code_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::_internal_mutable_code() {
  
  return _impl_.code_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::release_code() {
  // @@protoc_insertion_point(field_release:oj.mq.JudgeTaskMessage.code)
  return _impl_.code_.Release();
}
inline void JudgeTaskMessage::set_allocated_code(std::string* code) {
  if (code != nullptr) {
    
  } else {
    
  }
  _impl_.code_.SetAllocated(code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.code_.IsDefault()) {
    _impl_.code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.JudgeTaskMessage.code)
}

// string language = 5;
inline void JudgeTaskMessage::clear_language() {
  _impl_.language_.ClearToEmpty();
}
inline const std::string& JudgeTaskMessage::language() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.language)
  return _internal_language();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeTaskMessage::set_language(ArgT0&& arg0, ArgT... args) {
 
 _impl_.language_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.language)
}
inline std::string* JudgeTaskMessage::mutable_language() {
  std::string* _s = _internal_mutable_language();
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeTaskMessage.language)
  return _s;
}
inline const std::string& JudgeTaskMessage::_internal_language() const {
  return _impl_.language_.Get();
}
inline void JudgeTaskMessage::_internal_set_language(const std::string& value) {
  
  _impl_.language_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::_internal_mutable_language() {
  
  return _impl_.language_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::release_language() {
  // @@protoc_insertion_point(field_release:oj.mq.JudgeTaskMessage.language)
  return _impl_.language_.Release();
}
inline void JudgeTaskMessage::set_allocated_language(std::string* language) {
  if (language != nullptr) {
    
  } else {
    
  }
  _impl_.language_.SetAllocated(language, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.language_.IsDefault()) {
    _impl_.language_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.JudgeTaskMessage.language)
}

// bool is_custom_test = 6;
inline void JudgeTaskMessage::clear_is_custom_test() {
  _impl_.is_custom_test_ = false;
}
inline bool JudgeTaskMessage::_internal_is_custom_test() const {
  return _impl_.is_custom_test_;
}
inline bool JudgeTaskMessage::is_custom_test() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.is_custom_test)
  return _internal_is_custom_test();
}
inline void JudgeTaskMessage::_internal_set_is_custom_test(bool value) {
  
  _impl_.is_custom_test_ = value;
}
inline void JudgeTaskMessage::set_is_custom_test(bool value) {
  _internal_set_is_custom_test(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.is_custom_test)
}

// string custom_input = 7;
inline void JudgeTaskMessage::clear_custom_input() {
  _impl_.custom_input_.ClearToEmpty();
}
inline const std::string& JudgeTaskMessage::custom_input() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.custom_input)
  return _internal_custom_input();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeTaskMessage::set_custom_input(ArgT0&& arg0, ArgT... args) {
 
 _impl_.custom_input_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.custom_input)
}
inline std::string* JudgeTaskMessage::mutable_custom_input() {
  std::string* _s = _internal_mutable_custom_input();
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeTaskMessage.custom_input)
  return _s;
}
inline const std::string& JudgeTaskMessage::_internal_custom_input() const {
  return _impl_.custom_input_.Get();
}
inline void JudgeTaskMessage::_internal_set_custom_input(const std::string& value) {
  
  _impl_.custom_input_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::_internal_mutable_custom_input() {
  
  return _impl_.custom_input_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::release_custom_input() {
  // @@protoc_insertion_point(field_release:oj.mq.JudgeTaskMessage.custom_input)
  return _impl_.custom_input_.Release();
}
inline void JudgeTaskMessage::set_allocated_custom_input(std::string* custom_input) {
  if (custom_input != nullptr) {
    
  } else {
    
  }
  _impl_.custom_input_.SetAllocated(custom_input, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.custom_input_.IsDefault()) {
    _impl_.custom_input_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.JudgeTaskMessage.custom_input)
}

// int32 time_limit = 8;
inline void JudgeTaskMessage::clear_time_limit() {
  _impl_.time_limit_ = 0;
}
inline int32_t JudgeTaskMessage::_internal_time_limit() const {
  return _impl_.time_limit_;
}
inline int32_t JudgeTaskMessage::time_limit() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.time_limit)
  return _internal_time_limit();
}
inline void JudgeTaskMessage::_internal_set_time_limit(int32_t value) {
  
  _impl_.time_limit_ = value;
}
inline void JudgeTaskMessage::set_time_limit(int32_t value) {
  _internal_set_time_limit(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.time_limit)
}

// int32 memory_limit = 9;
inline void JudgeTaskMessage::clear_memory_limit() {
  _impl_.memory_limit_ = 0;
}
inline int32_t JudgeTaskMessage::_internal_memory_limit() const {
  return _impl_.memory_limit_;
}
inline int32_t JudgeTaskMessage::memory_limit() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.memory_limit)
  return _internal_memory_limit();
}
inline void JudgeTaskMessage::_internal_set_memory_limit(int32_t value) {
  
  _impl_.memory_limit_ = value;
}
inline void JudgeTaskMessage::set_memory_limit(int32_t value) {
  _internal_set_memory_limit(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.memory_limit)
}

// int64 timestamp = 10;
inline void JudgeTaskMessage::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t JudgeTaskMessage::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t JudgeTaskMessage::timestamp() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.timestamp)
  return _internal_timestamp();
}
inline void JudgeTaskMessage::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void JudgeTaskMessage::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.timestamp)
}

// uint32 retry_count = 11;
inline void JudgeTaskMessage::clear_retry_count() {
  _impl_.retry_count_ = 0u;
}
inline uint32_t JudgeTaskMessage::_internal_retry_count() const {
  return _impl_.retry_count_;
}
inline uint32_t JudgeTaskMessage::retry_count() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.retry_count)
  return _internal_retry_count();
}
inline void JudgeTaskMessage::_internal_set_retry_count(uint32_t value) {
  
  _impl_.retry_count_ = value;
}
inline void JudgeTaskMessage::set_retry_count(uint32_t value) {
  _internal_set_retry_count(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.retry_count)
}

// repeated .oj.mq.TestCaseInput test_cases = 12;
inline int JudgeTaskMessage::_internal_test_cases_size() const {
  return _impl_.test_cases_.size();
}
inline int JudgeTaskMessage::test_cases_size() const {
  return _internal_test_cases_size();
}
inline void JudgeTaskMessage::clear_test_cases() {
  _impl_.test_cases_.Clear();
}
inline ::oj::mq::TestCaseInput* JudgeTaskMessage::mutable_test_cases(int index) {
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeTaskMessage.test_cases)
  return _impl_.test_cases_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj::mq::TestCaseInput >*
JudgeTaskMessage::mutable_test_cases() {
  // @@protoc_insertion_point(field_mutable_list:oj.mq.JudgeTaskMessage.test_cases)
  return &_impl_.test_cases_;
}
inline const ::oj::mq::TestCaseInput& JudgeTaskMessage::_internal_test_cases(int index) const {
  return _impl_.test_cases_.Get(index);
}
inline const ::oj::mq::TestCaseInput& JudgeTaskMessage::test_cases(int index) const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.test_cases)
  return _internal_test_cases(index);
}
inline ::oj::mq::TestCaseInput* JudgeTaskMessage::_internal_add_test_cases() {
  return _impl_.test_cases_.Add();
}
inline ::oj::mq::TestCaseInput* JudgeTaskMessage::add_test_cases() {
  ::oj::mq::TestCaseInput* _add = _internal_add_test_cases();
  // @@protoc_insertion_point(field_add:oj.mq.JudgeTaskMessage.test_cases)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj::mq::TestCaseInput >&
JudgeTaskMessage::test_cases() const {
  // @@protoc_insertion_point(field_list:oj.mq.JudgeTaskMessage.test_cases)
  return _impl_.test_cases_;
}

// -------------------------------------------------------------------

// JudgeResultCallback

// uint32 submission_id = 1;
inline void JudgeResultCallback::clear_submission_id() {
  _impl_.submission_id_ = 0u;
}
inline uint32_t JudgeResultCallback::_internal_submission_id() const {
  return _impl_.submission_id_;
}
inline uint32_t JudgeResultCallback::submission_id() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeResultCallback.submission_id)
  return _internal_submission_id();
}
inline void JudgeResultCallback::_internal_set_submission_id(uint32_t value) {
  
  _impl_.submission_id_ = value;
}
inline void JudgeResultCallback::set_submission_id(uint32_t value) {
  _internal_set_submission_id(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeResultCallback.submission_id)
}

// string status = 2;
inline void JudgeResultCallback::clear_status() {
  _impl_.status_.ClearToEmpty();
}
inline const std::string& JudgeResultCallback::status() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeResultCallback.status)
  return _internal_status();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeResultCallback::set_status(ArgT0&& arg0, ArgT... args) {
 
 _impl_.status_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.JudgeResultCallback.status)
}
inline std::string* JudgeResultCallback::mutable_status() {
  std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeResultCallback.status)
  return _s;
}
inline const std::string& JudgeResultCallback::_internal_status() const {
  return _impl_.status_.Get();
}
inline void JudgeResultCallback::_internal_set_status(const std::string& value) {
  
  _impl_.status_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeResultCallback::_internal_mutable_status() {
  
  return _impl_.status_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeResultCallback::release_status() {
  // @@protoc_insertion_point(field_release:oj.mq.JudgeResultCallback.status)
  return _impl_.status_.Release();
}
inline void JudgeResultCallback::set_allocated_status(std::string* status) {
  if (status != nullptr) {
    
  } else {
    
  }
  _impl_.status_.SetAllocated(status, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.JudgeResultCallback.status)
}

// int32 time_used_ms = 3;
inline void JudgeResultCallback::clear_time_used_ms() {
  _impl_.time_used_ms_ = 0;
}
inline int32_t JudgeResultCallback::_internal_time_used_ms() const {
  return _impl_.time_used_ms_;
}
inline int32_t JudgeResultCallback::time_used_ms() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeResultCallback.time_used_ms)
  return _internal_time_used_ms();
}
inline void JudgeResultCallback::_internal_set_time_used_ms(int32_t value) {
  
  _impl_.time_used_ms_ = value;
}
inline void JudgeResultCallback::set_time_used_ms(int32_t value) {
  _internal_set_time_used_ms(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeResultCallback.time_used_ms)
}

// int64 memory_used_bytes = 4;
inline void JudgeResultCallback::clear_memory_used_bytes() {
  _impl_.memory_used_bytes_ = int64_t{0};
}
inline int64_t JudgeResultCallback::_internal_memory_used_bytes() const {
  return _impl_.memory_used_bytes_;
}
inline int64_t JudgeResultCallback::memory_used_bytes() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeResultCallback.memory_used_bytes)
  return _internal_memory_used_bytes();
}
inline void JudgeResultCallback::_internal_set_memory_used_bytes(int64_t value) {
  
  _impl_.memory_used_bytes_ = value;
}
inline void JudgeResultCallback::set_memory_used_bytes(int64_t value) {
  _internal_set_memory_used_bytes(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeResultCallback.memory_used_bytes)
}

// string compile_error = 5;
inline void JudgeResultCallback::clear_compile_error() {
  _impl_.compile_error_.ClearToEmpty();
}
inline const std::string& JudgeResultCallback::compile_error() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeResultCallback.compile_error)
  return _internal_compile_error();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeResultCallback::set_compile_error(ArgT0&& arg0, ArgT... args) {
 
 _impl_.compile_error_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.JudgeResultCallback.compile_error)
}
inline std::string* JudgeResultCallback::mutable_compile_error() {
  std::string* _s = _internal_mutable_compile_error();
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeResultCallback.compile_error)
  return _s;
}
inline const std::string& JudgeResultCallback::_internal_compile_error() const {
  return _impl_.compile_error_.Get();
}
inline void JudgeResultCallback::_internal_set_compile_error(const std::string& value) {
  
  _impl_.compile_error_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeResultCallback::_internal_mutable_compile_error() {
  
  return _impl_.compile_error_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeResultCallback::release_compile_error() {
  // @@protoc_insertion_point(field_release:oj.mq.JudgeResultCallback.compile_error)
  return _impl_.compile_error_.Release();
}
inline void JudgeResultCallback::set_allocated_compile_error(std::string* compile_error) {
  if (compile_error != nullptr) {
    
  } else {
    
  }
  _impl_.compile_error_.SetAllocated(compile_error, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.compile_error_.IsDefault()) {
    _impl_.compile_error_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.JudgeResultCallback.compile_error)
}

// string test_cases_json = 6;
inline void JudgeResultCallback::clear_test_cases_json() {
  _impl_.test_cases_json_.ClearToEmpty();
}
inline const std::string& JudgeResultCallback::test_cases_json() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeResultCallback.test_cases_json)
  return _internal_test_cases_json();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeResultCallback::set_test_cases_json(ArgT0&& arg0, ArgT... args) {
 
 _impl_.test_cases_json_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.JudgeResultCallback.test_cases_json)
}
inline std::string* JudgeResultCallback::mutable_test_cases_json() {
  std::string* _s = _internal_mutable_test_cases_json();
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeResultCallback.test_cases_json)
  return _s;
}
inline const std::string& JudgeResultCallback::_internal_test_cases_json() const {
  return _impl_.test_cases_json_.Get();
}
inline void JudgeResultCallback::_internal_set_test_cases_json(const std::string& value) {
  
  _impl_.test_cases_json_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeResultCallback::_internal_mutable_test_cases_json() {
  
  return _impl_.test_cases_json_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeResultCallback::release_test_cases_json() {
  // @@protoc_insertion_point(field_release:oj.mq.JudgeResultCallback.test_cases_json)
  return _impl_.test_cases_json_.Release();
}
inline void JudgeResultCallback::set_allocated_test_cases_json(std::string* test_cases_json) {
  if (test_cases_json != nullptr) {
    
  } else {
    
  }
  _impl_.test_cases_json_.SetAllocated(test_cases_json, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.test_cases_json_.IsDefault()) {
    _impl_.test_cases_json_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.JudgeResultCallback.test_cases_json)
}

// int64 completed_at = 7;
inline void JudgeResultCallback::clear_completed_at() {
  _impl_.completed_at_ = int64_t{0};
}
inline int64_t JudgeResultCallback::_internal_completed_at() const {
  return _impl_.completed_at_;
}
inline int64_t JudgeResultCallback::completed_at() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeResultCallback.completed_at)
  return _internal_completed_at();
}
inline void JudgeResultCallback::_internal_set_completed_at(int64_t value) {
  
  _impl_.completed_at_ = value;
}
inline void JudgeResultCallback::set_completed_at(int64_t value) {
  _internal_set_completed_at(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeResultCallback.completed_at)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mq
}  // namespace oj

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mq_5fmessage_2eproto
