// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mq_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mq_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mq_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mq_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mq_5fmessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mq_5fmessage_2eproto;
namespace oj {
namespace mq {
class JudgeTaskMessage;
struct JudgeTaskMessageDefaultTypeInternal;
extern JudgeTaskMessageDefaultTypeInternal _JudgeTaskMessage_default_instance_;
class TestCaseInput;
struct TestCaseInputDefaultTypeInternal;
extern TestCaseInputDefaultTypeInternal _TestCaseInput_default_instance_;
}  // namespace mq
}  // namespace oj
PROTOBUF_NAMESPACE_OPEN
template<> ::oj::mq::JudgeTaskMessage* Arena::CreateMaybeMessage<::oj::mq::JudgeTaskMessage>(Arena*);
template<> ::oj::mq::TestCaseInput* Arena::CreateMaybeMessage<::oj::mq::TestCaseInput>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace oj {
namespace mq {

// ===================================================================

class TestCaseInput final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj.mq.TestCaseInput) */ {
 public:
  inline TestCaseInput() : TestCaseInput(nullptr) {}
  ~TestCaseInput() override;
  explicit PROTOBUF_CONSTEXPR TestCaseInput(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TestCaseInput(const TestCaseInput& from);
  TestCaseInput(TestCaseInput&& from) noexcept
    : TestCaseInput() {
    *this = ::std::move(from);
  }

  inline TestCaseInput& operator=(const TestCaseInput& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestCaseInput& operator=(TestCaseInput&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestCaseInput& default_instance() {
    return *internal_default_instance();
  }
  static inline const TestCaseInput* internal_default_instance() {
    return reinterpret_cast<const TestCaseInput*>(
               &_TestCaseInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TestCaseInput& a, TestCaseInput& b) {
    a.Swap(&b);
  }
  inline void Swap(TestCaseInput* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestCaseInput* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestCaseInput* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TestCaseInput>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TestCaseInput& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TestCaseInput& from) {
    TestCaseInput::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestCaseInput* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj.mq.TestCaseInput";
  }
  protected:
  explicit TestCaseInput(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInputFieldNumber = 3,
    kExpectedOutputFieldNumber = 4,
    kTestCaseIdFieldNumber = 1,
    kIndexFieldNumber = 2,
  };
  // string input = 3;
  void clear_input();
  const std::string& input() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_input(ArgT0&& arg0, ArgT... args);
  std::string* mutable_input();
  PROTOBUF_NODISCARD std::string* release_input();
  void set_allocated_input(std::string* input);
  private:
  const std::string& _internal_input() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_input(const std::string& value);
  std::string* _internal_mutable_input();
  public:

  // string expected_output = 4;
  void clear_expected_output();
  const std::string& expected_output() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_expected_output(ArgT0&& arg0, ArgT... args);
  std::string* mutable_expected_output();
  PROTOBUF_NODISCARD std::string* release_expected_output();
  void set_allocated_expected_output(std::string* expected_output);
  private:
  const std::string& _internal_expected_output() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_expected_output(const std::string& value);
  std::string* _internal_mutable_expected_output();
  public:

  // uint64 test_case_id = 1;
  void clear_test_case_id();
  uint64_t test_case_id() const;
  void set_test_case_id(uint64_t value);
  private:
  uint64_t _internal_test_case_id() const;
  void _internal_set_test_case_id(uint64_t value);
  public:

  // uint32 index = 2;
  void clear_index();
  uint32_t index() const;
  void set_index(uint32_t value);
  private:
  uint32_t _internal_index() const;
  void _internal_set_index(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:oj.mq.TestCaseInput)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr input_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr expected_output_;
    uint64_t test_case_id_;
    uint32_t index_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mq_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class JudgeTaskMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oj.mq.JudgeTaskMessage) */ {
 public:
  inline JudgeTaskMessage() : JudgeTaskMessage(nullptr) {}
  ~JudgeTaskMessage() override;
  explicit PROTOBUF_CONSTEXPR JudgeTaskMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JudgeTaskMessage(const JudgeTaskMessage& from);
  JudgeTaskMessage(JudgeTaskMessage&& from) noexcept
    : JudgeTaskMessage() {
    *this = ::std::move(from);
  }

  inline JudgeTaskMessage& operator=(const JudgeTaskMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline JudgeTaskMessage& operator=(JudgeTaskMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JudgeTaskMessage& default_instance() {
    return *internal_default_instance();
  }
  enum TaskIdCase {
    kSubmissionId = 3,
    kCustomTaskId = 4,
    TASK_ID_NOT_SET = 0,
  };

  static inline const JudgeTaskMessage* internal_default_instance() {
    return reinterpret_cast<const JudgeTaskMessage*>(
               &_JudgeTaskMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(JudgeTaskMessage& a, JudgeTaskMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(JudgeTaskMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JudgeTaskMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JudgeTaskMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JudgeTaskMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JudgeTaskMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JudgeTaskMessage& from) {
    JudgeTaskMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JudgeTaskMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oj.mq.JudgeTaskMessage";
  }
  protected:
  explicit JudgeTaskMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTestCasesFieldNumber = 12,
    kMessageIdFieldNumber = 1,
    kQuestionIdFieldNumber = 6,
    kCodeFieldNumber = 7,
    kLanguageFieldNumber = 8,
    kCustomInputFieldNumber = 11,
    kUserIdFieldNumber = 5,
    kTimeLimitMsFieldNumber = 9,
    kMemoryLimitMbFieldNumber = 10,
    kDeliveryAttemptFieldNumber = 14,
    kCreatedAtFieldNumber = 13,
    kSubmissionIdFieldNumber = 3,
    kCustomTaskIdFieldNumber = 4,
  };
  // repeated .oj.mq.TestCaseInput test_cases = 12;
  int test_cases_size() const;
  private:
  int _internal_test_cases_size() const;
  public:
  void clear_test_cases();
  ::oj::mq::TestCaseInput* mutable_test_cases(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj::mq::TestCaseInput >*
      mutable_test_cases();
  private:
  const ::oj::mq::TestCaseInput& _internal_test_cases(int index) const;
  ::oj::mq::TestCaseInput* _internal_add_test_cases();
  public:
  const ::oj::mq::TestCaseInput& test_cases(int index) const;
  ::oj::mq::TestCaseInput* add_test_cases();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj::mq::TestCaseInput >&
      test_cases() const;

  // string message_id = 1;
  void clear_message_id();
  const std::string& message_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message_id();
  PROTOBUF_NODISCARD std::string* release_message_id();
  void set_allocated_message_id(std::string* message_id);
  private:
  const std::string& _internal_message_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message_id(const std::string& value);
  std::string* _internal_mutable_message_id();
  public:

  // string question_id = 6;
  void clear_question_id();
  const std::string& question_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_question_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_question_id();
  PROTOBUF_NODISCARD std::string* release_question_id();
  void set_allocated_question_id(std::string* question_id);
  private:
  const std::string& _internal_question_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_question_id(const std::string& value);
  std::string* _internal_mutable_question_id();
  public:

  // string code = 7;
  void clear_code();
  const std::string& code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_code();
  PROTOBUF_NODISCARD std::string* release_code();
  void set_allocated_code(std::string* code);
  private:
  const std::string& _internal_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_code(const std::string& value);
  std::string* _internal_mutable_code();
  public:

  // string language = 8;
  void clear_language();
  const std::string& language() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_language(ArgT0&& arg0, ArgT... args);
  std::string* mutable_language();
  PROTOBUF_NODISCARD std::string* release_language();
  void set_allocated_language(std::string* language);
  private:
  const std::string& _internal_language() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_language(const std::string& value);
  std::string* _internal_mutable_language();
  public:

  // string custom_input = 11;
  void clear_custom_input();
  const std::string& custom_input() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_custom_input(ArgT0&& arg0, ArgT... args);
  std::string* mutable_custom_input();
  PROTOBUF_NODISCARD std::string* release_custom_input();
  void set_allocated_custom_input(std::string* custom_input);
  private:
  const std::string& _internal_custom_input() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_custom_input(const std::string& value);
  std::string* _internal_mutable_custom_input();
  public:

  // uint32 user_id = 5;
  void clear_user_id();
  uint32_t user_id() const;
  void set_user_id(uint32_t value);
  private:
  uint32_t _internal_user_id() const;
  void _internal_set_user_id(uint32_t value);
  public:

  // uint32 time_limit_ms = 9;
  void clear_time_limit_ms();
  uint32_t time_limit_ms() const;
  void set_time_limit_ms(uint32_t value);
  private:
  uint32_t _internal_time_limit_ms() const;
  void _internal_set_time_limit_ms(uint32_t value);
  public:

  // uint32 memory_limit_mb = 10;
  void clear_memory_limit_mb();
  uint32_t memory_limit_mb() const;
  void set_memory_limit_mb(uint32_t value);
  private:
  uint32_t _internal_memory_limit_mb() const;
  void _internal_set_memory_limit_mb(uint32_t value);
  public:

  // uint32 delivery_attempt = 14;
  void clear_delivery_attempt();
  uint32_t delivery_attempt() const;
  void set_delivery_attempt(uint32_t value);
  private:
  uint32_t _internal_delivery_attempt() const;
  void _internal_set_delivery_attempt(uint32_t value);
  public:

  // int64 created_at = 13;
  void clear_created_at();
  int64_t created_at() const;
  void set_created_at(int64_t value);
  private:
  int64_t _internal_created_at() const;
  void _internal_set_created_at(int64_t value);
  public:

  // uint64 submission_id = 3;
  bool has_submission_id() const;
  private:
  bool _internal_has_submission_id() const;
  public:
  void clear_submission_id();
  uint64_t submission_id() const;
  void set_submission_id(uint64_t value);
  private:
  uint64_t _internal_submission_id() const;
  void _internal_set_submission_id(uint64_t value);
  public:

  // string custom_task_id = 4;
  bool has_custom_task_id() const;
  private:
  bool _internal_has_custom_task_id() const;
  public:
  void clear_custom_task_id();
  const std::string& custom_task_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_custom_task_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_custom_task_id();
  PROTOBUF_NODISCARD std::string* release_custom_task_id();
  void set_allocated_custom_task_id(std::string* custom_task_id);
  private:
  const std::string& _internal_custom_task_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_custom_task_id(const std::string& value);
  std::string* _internal_mutable_custom_task_id();
  public:

  void clear_task_id();
  TaskIdCase task_id_case() const;
  // @@protoc_insertion_point(class_scope:oj.mq.JudgeTaskMessage)
 private:
  class _Internal;
  void set_has_submission_id();
  void set_has_custom_task_id();

  inline bool has_task_id() const;
  inline void clear_has_task_id();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj::mq::TestCaseInput > test_cases_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr question_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr code_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr language_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr custom_input_;
    uint32_t user_id_;
    uint32_t time_limit_ms_;
    uint32_t memory_limit_mb_;
    uint32_t delivery_attempt_;
    int64_t created_at_;
    union TaskIdUnion {
      constexpr TaskIdUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      uint64_t submission_id_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr custom_task_id_;
    } task_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mq_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TestCaseInput

// uint64 test_case_id = 1;
inline void TestCaseInput::clear_test_case_id() {
  _impl_.test_case_id_ = uint64_t{0u};
}
inline uint64_t TestCaseInput::_internal_test_case_id() const {
  return _impl_.test_case_id_;
}
inline uint64_t TestCaseInput::test_case_id() const {
  // @@protoc_insertion_point(field_get:oj.mq.TestCaseInput.test_case_id)
  return _internal_test_case_id();
}
inline void TestCaseInput::_internal_set_test_case_id(uint64_t value) {

  _impl_.test_case_id_ = value;
}
inline void TestCaseInput::set_test_case_id(uint64_t value) {
  _internal_set_test_case_id(value);
  // @@protoc_insertion_point(field_set:oj.mq.TestCaseInput.test_case_id)
}

// uint32 index = 2;
inline void TestCaseInput::clear_index() {
  _impl_.index_ = 0u;
}
inline uint32_t TestCaseInput::_internal_index() const {
  return _impl_.index_;
}
inline uint32_t TestCaseInput::index() const {
  // @@protoc_insertion_point(field_get:oj.mq.TestCaseInput.index)
  return _internal_index();
}
inline void TestCaseInput::_internal_set_index(uint32_t value) {

  _impl_.index_ = value;
}
inline void TestCaseInput::set_index(uint32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:oj.mq.TestCaseInput.index)
}

// string input = 3;
inline void TestCaseInput::clear_input() {
  _impl_.input_.ClearToEmpty();
}
inline const std::string& TestCaseInput::input() const {
  // @@protoc_insertion_point(field_get:oj.mq.TestCaseInput.input)
  return _internal_input();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TestCaseInput::set_input(ArgT0&& arg0, ArgT... args) {

 _impl_.input_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.TestCaseInput.input)
}
inline std::string* TestCaseInput::mutable_input() {
  std::string* _s = _internal_mutable_input();
  // @@protoc_insertion_point(field_mutable:oj.mq.TestCaseInput.input)
  return _s;
}
inline const std::string& TestCaseInput::_internal_input() const {
  return _impl_.input_.Get();
}
inline void TestCaseInput::_internal_set_input(const std::string& value) {

  _impl_.input_.Set(value, GetArenaForAllocation());
}
inline std::string* TestCaseInput::_internal_mutable_input() {

  return _impl_.input_.Mutable(GetArenaForAllocation());
}
inline std::string* TestCaseInput::release_input() {
  // @@protoc_insertion_point(field_release:oj.mq.TestCaseInput.input)
  return _impl_.input_.Release();
}
inline void TestCaseInput::set_allocated_input(std::string* input) {
  if (input != nullptr) {

  } else {

  }
  _impl_.input_.SetAllocated(input, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.input_.IsDefault()) {
    _impl_.input_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.TestCaseInput.input)
}

// string expected_output = 4;
inline void TestCaseInput::clear_expected_output() {
  _impl_.expected_output_.ClearToEmpty();
}
inline const std::string& TestCaseInput::expected_output() const {
  // @@protoc_insertion_point(field_get:oj.mq.TestCaseInput.expected_output)
  return _internal_expected_output();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TestCaseInput::set_expected_output(ArgT0&& arg0, ArgT... args) {

 _impl_.expected_output_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.TestCaseInput.expected_output)
}
inline std::string* TestCaseInput::mutable_expected_output() {
  std::string* _s = _internal_mutable_expected_output();
  // @@protoc_insertion_point(field_mutable:oj.mq.TestCaseInput.expected_output)
  return _s;
}
inline const std::string& TestCaseInput::_internal_expected_output() const {
  return _impl_.expected_output_.Get();
}
inline void TestCaseInput::_internal_set_expected_output(const std::string& value) {

  _impl_.expected_output_.Set(value, GetArenaForAllocation());
}
inline std::string* TestCaseInput::_internal_mutable_expected_output() {

  return _impl_.expected_output_.Mutable(GetArenaForAllocation());
}
inline std::string* TestCaseInput::release_expected_output() {
  // @@protoc_insertion_point(field_release:oj.mq.TestCaseInput.expected_output)
  return _impl_.expected_output_.Release();
}
inline void TestCaseInput::set_allocated_expected_output(std::string* expected_output) {
  if (expected_output != nullptr) {

  } else {

  }
  _impl_.expected_output_.SetAllocated(expected_output, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.expected_output_.IsDefault()) {
    _impl_.expected_output_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.TestCaseInput.expected_output)
}

// -------------------------------------------------------------------

// JudgeTaskMessage

// string message_id = 1;
inline void JudgeTaskMessage::clear_message_id() {
  _impl_.message_id_.ClearToEmpty();
}
inline const std::string& JudgeTaskMessage::message_id() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.message_id)
  return _internal_message_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeTaskMessage::set_message_id(ArgT0&& arg0, ArgT... args) {

 _impl_.message_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.message_id)
}
inline std::string* JudgeTaskMessage::mutable_message_id() {
  std::string* _s = _internal_mutable_message_id();
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeTaskMessage.message_id)
  return _s;
}
inline const std::string& JudgeTaskMessage::_internal_message_id() const {
  return _impl_.message_id_.Get();
}
inline void JudgeTaskMessage::_internal_set_message_id(const std::string& value) {

  _impl_.message_id_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::_internal_mutable_message_id() {

  return _impl_.message_id_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::release_message_id() {
  // @@protoc_insertion_point(field_release:oj.mq.JudgeTaskMessage.message_id)
  return _impl_.message_id_.Release();
}
inline void JudgeTaskMessage::set_allocated_message_id(std::string* message_id) {
  if (message_id != nullptr) {

  } else {

  }
  _impl_.message_id_.SetAllocated(message_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_id_.IsDefault()) {
    _impl_.message_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.JudgeTaskMessage.message_id)
}

// uint64 submission_id = 3;
inline bool JudgeTaskMessage::_internal_has_submission_id() const {
  return task_id_case() == kSubmissionId;
}
inline bool JudgeTaskMessage::has_submission_id() const {
  return _internal_has_submission_id();
}
inline void JudgeTaskMessage::set_has_submission_id() {
  _impl_._oneof_case_[0] = kSubmissionId;
}
inline void JudgeTaskMessage::clear_submission_id() {
  if (_internal_has_submission_id()) {
    _impl_.task_id_.submission_id_ = uint64_t{0u};
    clear_has_task_id();
  }
}
inline uint64_t JudgeTaskMessage::_internal_submission_id() const {
  if (_internal_has_submission_id()) {
    return _impl_.task_id_.submission_id_;
  }
  return uint64_t{0u};
}
inline void JudgeTaskMessage::_internal_set_submission_id(uint64_t value) {
  if (!_internal_has_submission_id()) {
    clear_task_id();
    set_has_submission_id();
  }
  _impl_.task_id_.submission_id_ = value;
}
inline uint64_t JudgeTaskMessage::submission_id() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.submission_id)
  return _internal_submission_id();
}
inline void JudgeTaskMessage::set_submission_id(uint64_t value) {
  _internal_set_submission_id(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.submission_id)
}

// string custom_task_id = 4;
inline bool JudgeTaskMessage::_internal_has_custom_task_id() const {
  return task_id_case() == kCustomTaskId;
}
inline bool JudgeTaskMessage::has_custom_task_id() const {
  return _internal_has_custom_task_id();
}
inline void JudgeTaskMessage::set_has_custom_task_id() {
  _impl_._oneof_case_[0] = kCustomTaskId;
}
inline void JudgeTaskMessage::clear_custom_task_id() {
  if (_internal_has_custom_task_id()) {
    _impl_.task_id_.custom_task_id_.Destroy();
    clear_has_task_id();
  }
}
inline const std::string& JudgeTaskMessage::custom_task_id() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.custom_task_id)
  return _internal_custom_task_id();
}
template <typename ArgT0, typename... ArgT>
inline void JudgeTaskMessage::set_custom_task_id(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_custom_task_id()) {
    clear_task_id();
    set_has_custom_task_id();
    _impl_.task_id_.custom_task_id_.InitDefault();
  }
  _impl_.task_id_.custom_task_id_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.custom_task_id)
}
inline std::string* JudgeTaskMessage::mutable_custom_task_id() {
  std::string* _s = _internal_mutable_custom_task_id();
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeTaskMessage.custom_task_id)
  return _s;
}
inline const std::string& JudgeTaskMessage::_internal_custom_task_id() const {
  if (_internal_has_custom_task_id()) {
    return _impl_.task_id_.custom_task_id_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void JudgeTaskMessage::_internal_set_custom_task_id(const std::string& value) {
  if (!_internal_has_custom_task_id()) {
    clear_task_id();
    set_has_custom_task_id();
    _impl_.task_id_.custom_task_id_.InitDefault();
  }
  _impl_.task_id_.custom_task_id_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::_internal_mutable_custom_task_id() {
  if (!_internal_has_custom_task_id()) {
    clear_task_id();
    set_has_custom_task_id();
    _impl_.task_id_.custom_task_id_.InitDefault();
  }
  return _impl_.task_id_.custom_task_id_.Mutable(      GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::release_custom_task_id() {
  // @@protoc_insertion_point(field_release:oj.mq.JudgeTaskMessage.custom_task_id)
  if (_internal_has_custom_task_id()) {
    clear_has_task_id();
    return _impl_.task_id_.custom_task_id_.Release();
  } else {
    return nullptr;
  }
}
inline void JudgeTaskMessage::set_allocated_custom_task_id(std::string* custom_task_id) {
  if (has_task_id()) {
    clear_task_id();
  }
  if (custom_task_id != nullptr) {
    set_has_custom_task_id();
    _impl_.task_id_.custom_task_id_.InitAllocated(custom_task_id, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:oj.mq.JudgeTaskMessage.custom_task_id)
}

// uint32 user_id = 5;
inline void JudgeTaskMessage::clear_user_id() {
  _impl_.user_id_ = 0u;
}
inline uint32_t JudgeTaskMessage::_internal_user_id() const {
  return _impl_.user_id_;
}
inline uint32_t JudgeTaskMessage::user_id() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.user_id)
  return _internal_user_id();
}
inline void JudgeTaskMessage::_internal_set_user_id(uint32_t value) {

  _impl_.user_id_ = value;
}
inline void JudgeTaskMessage::set_user_id(uint32_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.user_id)
}

// string question_id = 6;
inline void JudgeTaskMessage::clear_question_id() {
  _impl_.question_id_.ClearToEmpty();
}
inline const std::string& JudgeTaskMessage::question_id() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.question_id)
  return _internal_question_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeTaskMessage::set_question_id(ArgT0&& arg0, ArgT... args) {

 _impl_.question_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.question_id)
}
inline std::string* JudgeTaskMessage::mutable_question_id() {
  std::string* _s = _internal_mutable_question_id();
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeTaskMessage.question_id)
  return _s;
}
inline const std::string& JudgeTaskMessage::_internal_question_id() const {
  return _impl_.question_id_.Get();
}
inline void JudgeTaskMessage::_internal_set_question_id(const std::string& value) {

  _impl_.question_id_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::_internal_mutable_question_id() {

  return _impl_.question_id_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::release_question_id() {
  // @@protoc_insertion_point(field_release:oj.mq.JudgeTaskMessage.question_id)
  return _impl_.question_id_.Release();
}
inline void JudgeTaskMessage::set_allocated_question_id(std::string* question_id) {
  if (question_id != nullptr) {

  } else {

  }
  _impl_.question_id_.SetAllocated(question_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.question_id_.IsDefault()) {
    _impl_.question_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.JudgeTaskMessage.question_id)
}

// string code = 7;
inline void JudgeTaskMessage::clear_code() {
  _impl_.code_.ClearToEmpty();
}
inline const std::string& JudgeTaskMessage::code() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.code)
  return _internal_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeTaskMessage::set_code(ArgT0&& arg0, ArgT... args) {

 _impl_.code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.code)
}
inline std::string* JudgeTaskMessage::mutable_code() {
  std::string* _s = _internal_mutable_code();
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeTaskMessage.code)
  return _s;
}
inline const std::string& JudgeTaskMessage::_internal_code() const {
  return _impl_.code_.Get();
}
inline void JudgeTaskMessage::_internal_set_code(const std::string& value) {

  _impl_.code_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::_internal_mutable_code() {

  return _impl_.code_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::release_code() {
  // @@protoc_insertion_point(field_release:oj.mq.JudgeTaskMessage.code)
  return _impl_.code_.Release();
}
inline void JudgeTaskMessage::set_allocated_code(std::string* code) {
  if (code != nullptr) {

  } else {

  }
  _impl_.code_.SetAllocated(code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.code_.IsDefault()) {
    _impl_.code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.JudgeTaskMessage.code)
}

// string language = 8;
inline void JudgeTaskMessage::clear_language() {
  _impl_.language_.ClearToEmpty();
}
inline const std::string& JudgeTaskMessage::language() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.language)
  return _internal_language();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeTaskMessage::set_language(ArgT0&& arg0, ArgT... args) {

 _impl_.language_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.language)
}
inline std::string* JudgeTaskMessage::mutable_language() {
  std::string* _s = _internal_mutable_language();
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeTaskMessage.language)
  return _s;
}
inline const std::string& JudgeTaskMessage::_internal_language() const {
  return _impl_.language_.Get();
}
inline void JudgeTaskMessage::_internal_set_language(const std::string& value) {

  _impl_.language_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::_internal_mutable_language() {

  return _impl_.language_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::release_language() {
  // @@protoc_insertion_point(field_release:oj.mq.JudgeTaskMessage.language)
  return _impl_.language_.Release();
}
inline void JudgeTaskMessage::set_allocated_language(std::string* language) {
  if (language != nullptr) {

  } else {

  }
  _impl_.language_.SetAllocated(language, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.language_.IsDefault()) {
    _impl_.language_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.JudgeTaskMessage.language)
}

// uint32 time_limit_ms = 9;
inline void JudgeTaskMessage::clear_time_limit_ms() {
  _impl_.time_limit_ms_ = 0u;
}
inline uint32_t JudgeTaskMessage::_internal_time_limit_ms() const {
  return _impl_.time_limit_ms_;
}
inline uint32_t JudgeTaskMessage::time_limit_ms() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.time_limit_ms)
  return _internal_time_limit_ms();
}
inline void JudgeTaskMessage::_internal_set_time_limit_ms(uint32_t value) {

  _impl_.time_limit_ms_ = value;
}
inline void JudgeTaskMessage::set_time_limit_ms(uint32_t value) {
  _internal_set_time_limit_ms(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.time_limit_ms)
}

// uint32 memory_limit_mb = 10;
inline void JudgeTaskMessage::clear_memory_limit_mb() {
  _impl_.memory_limit_mb_ = 0u;
}
inline uint32_t JudgeTaskMessage::_internal_memory_limit_mb() const {
  return _impl_.memory_limit_mb_;
}
inline uint32_t JudgeTaskMessage::memory_limit_mb() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.memory_limit_mb)
  return _internal_memory_limit_mb();
}
inline void JudgeTaskMessage::_internal_set_memory_limit_mb(uint32_t value) {

  _impl_.memory_limit_mb_ = value;
}
inline void JudgeTaskMessage::set_memory_limit_mb(uint32_t value) {
  _internal_set_memory_limit_mb(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.memory_limit_mb)
}

// string custom_input = 11;
inline void JudgeTaskMessage::clear_custom_input() {
  _impl_.custom_input_.ClearToEmpty();
}
inline const std::string& JudgeTaskMessage::custom_input() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.custom_input)
  return _internal_custom_input();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeTaskMessage::set_custom_input(ArgT0&& arg0, ArgT... args) {

 _impl_.custom_input_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.custom_input)
}
inline std::string* JudgeTaskMessage::mutable_custom_input() {
  std::string* _s = _internal_mutable_custom_input();
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeTaskMessage.custom_input)
  return _s;
}
inline const std::string& JudgeTaskMessage::_internal_custom_input() const {
  return _impl_.custom_input_.Get();
}
inline void JudgeTaskMessage::_internal_set_custom_input(const std::string& value) {

  _impl_.custom_input_.Set(value, GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::_internal_mutable_custom_input() {

  return _impl_.custom_input_.Mutable(GetArenaForAllocation());
}
inline std::string* JudgeTaskMessage::release_custom_input() {
  // @@protoc_insertion_point(field_release:oj.mq.JudgeTaskMessage.custom_input)
  return _impl_.custom_input_.Release();
}
inline void JudgeTaskMessage::set_allocated_custom_input(std::string* custom_input) {
  if (custom_input != nullptr) {

  } else {

  }
  _impl_.custom_input_.SetAllocated(custom_input, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.custom_input_.IsDefault()) {
    _impl_.custom_input_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:oj.mq.JudgeTaskMessage.custom_input)
}

// repeated .oj.mq.TestCaseInput test_cases = 12;
inline int JudgeTaskMessage::_internal_test_cases_size() const {
  return _impl_.test_cases_.size();
}
inline int JudgeTaskMessage::test_cases_size() const {
  return _internal_test_cases_size();
}
inline void JudgeTaskMessage::clear_test_cases() {
  _impl_.test_cases_.Clear();
}
inline ::oj::mq::TestCaseInput* JudgeTaskMessage::mutable_test_cases(int index) {
  // @@protoc_insertion_point(field_mutable:oj.mq.JudgeTaskMessage.test_cases)
  return _impl_.test_cases_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj::mq::TestCaseInput >*
JudgeTaskMessage::mutable_test_cases() {
  // @@protoc_insertion_point(field_mutable_list:oj.mq.JudgeTaskMessage.test_cases)
  return &_impl_.test_cases_;
}
inline const ::oj::mq::TestCaseInput& JudgeTaskMessage::_internal_test_cases(int index) const {
  return _impl_.test_cases_.Get(index);
}
inline const ::oj::mq::TestCaseInput& JudgeTaskMessage::test_cases(int index) const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.test_cases)
  return _internal_test_cases(index);
}
inline ::oj::mq::TestCaseInput* JudgeTaskMessage::_internal_add_test_cases() {
  return _impl_.test_cases_.Add();
}
inline ::oj::mq::TestCaseInput* JudgeTaskMessage::add_test_cases() {
  ::oj::mq::TestCaseInput* _add = _internal_add_test_cases();
  // @@protoc_insertion_point(field_add:oj.mq.JudgeTaskMessage.test_cases)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oj::mq::TestCaseInput >&
JudgeTaskMessage::test_cases() const {
  // @@protoc_insertion_point(field_list:oj.mq.JudgeTaskMessage.test_cases)
  return _impl_.test_cases_;
}

// int64 created_at = 13;
inline void JudgeTaskMessage::clear_created_at() {
  _impl_.created_at_ = int64_t{0};
}
inline int64_t JudgeTaskMessage::_internal_created_at() const {
  return _impl_.created_at_;
}
inline int64_t JudgeTaskMessage::created_at() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.created_at)
  return _internal_created_at();
}
inline void JudgeTaskMessage::_internal_set_created_at(int64_t value) {

  _impl_.created_at_ = value;
}
inline void JudgeTaskMessage::set_created_at(int64_t value) {
  _internal_set_created_at(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.created_at)
}

// uint32 delivery_attempt = 14;
inline void JudgeTaskMessage::clear_delivery_attempt() {
  _impl_.delivery_attempt_ = 0u;
}
inline uint32_t JudgeTaskMessage::_internal_delivery_attempt() const {
  return _impl_.delivery_attempt_;
}
inline uint32_t JudgeTaskMessage::delivery_attempt() const {
  // @@protoc_insertion_point(field_get:oj.mq.JudgeTaskMessage.delivery_attempt)
  return _internal_delivery_attempt();
}
inline void JudgeTaskMessage::_internal_set_delivery_attempt(uint32_t value) {

  _impl_.delivery_attempt_ = value;
}
inline void JudgeTaskMessage::set_delivery_attempt(uint32_t value) {
  _internal_set_delivery_attempt(value);
  // @@protoc_insertion_point(field_set:oj.mq.JudgeTaskMessage.delivery_attempt)
}

inline bool JudgeTaskMessage::has_task_id() const {
  return task_id_case() != TASK_ID_NOT_SET;
}
inline void JudgeTaskMessage::clear_has_task_id() {
  _impl_._oneof_case_[0] = TASK_ID_NOT_SET;
}
inline JudgeTaskMessage::TaskIdCase JudgeTaskMessage::task_id_case() const {
  return JudgeTaskMessage::TaskIdCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mq
}  // namespace oj

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mq_5fmessage_2eproto
