-- Remove data generated by mysql_seed.sql from an isolated performance database.
-- This also removes submissions and interactions created by PERF users during a run.

SET NAMES utf8mb4;
SET SESSION sql_safe_updates = 0;

DELETE jr FROM judge_result_receipts jr
JOIN submissions s ON s.submission_id = jr.submission_id
LEFT JOIN users u ON u.uid = s.user_id
WHERE s.question_id LIKE 'P%' OR u.name LIKE 'perf_u%';

DELETE jo FROM judge_outbox jo
JOIN submissions s ON s.submission_id = jo.submission_id
LEFT JOIN users u ON u.uid = s.user_id
WHERE s.question_id LIKE 'P%' OR u.name LIKE 'perf_u%';

DELETE ca FROM comment_actions ca
LEFT JOIN solution_comments c ON c.id = ca.comment_id
LEFT JOIN solutions s ON s.id = c.solution_id
LEFT JOIN users u ON u.uid = ca.user_id
WHERE s.question_id LIKE 'P%' OR u.name LIKE 'perf_u%';

DELETE sa FROM solution_actions sa
LEFT JOIN solutions s ON s.id = sa.solution_id
LEFT JOIN users u ON u.uid = sa.user_id
WHERE s.question_id LIKE 'P%' OR u.name LIKE 'perf_u%';

DELETE c FROM solution_comments c
JOIN solutions s ON s.id = c.solution_id
WHERE s.question_id LIKE 'P%';

DELETE al FROM admin_audit_logs al
LEFT JOIN admin_accounts aa ON aa.admin_id = al.operator_admin_id
LEFT JOIN users u ON u.uid = aa.uid
WHERE al.request_id LIKE 'PERF-%' OR u.name LIKE 'perf_u%';

DELETE aa FROM admin_accounts aa
JOIN users u ON u.uid = aa.uid
WHERE u.name LIKE 'perf_u%';

DELETE FROM submissions
WHERE question_id LIKE 'P%'
   OR user_id IN (SELECT uid FROM users WHERE name LIKE 'perf_u%');

DELETE FROM user_submits
WHERE question_id LIKE 'P%'
   OR user_id IN (SELECT uid FROM users WHERE name LIKE 'perf_u%');

DELETE FROM solutions
WHERE question_id LIKE 'P%'
   OR user_id IN (SELECT uid FROM users WHERE name LIKE 'perf_u%');

DELETE FROM tests WHERE question_id LIKE 'P%';
DELETE FROM questions WHERE id LIKE 'P%';
DELETE FROM users WHERE name LIKE 'perf_u%' OR email LIKE 'perf_u%@perf.invalid';
COMMIT;

SELECT 'remaining_perf_users' AS check_name, COUNT(*) AS remaining
FROM users WHERE name LIKE 'perf_u%'
UNION ALL
SELECT 'remaining_perf_questions', COUNT(*) FROM questions WHERE id LIKE 'P%'
UNION ALL
SELECT 'remaining_perf_audit_logs', COUNT(*) FROM admin_audit_logs WHERE request_id LIKE 'PERF-%';
